// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.unified.unifiedws;

import com.kucoin.universal.sdk.internal.interfaces.WebSocketUnifiedService;
import com.kucoin.universal.sdk.model.UnifiedWsArgs;
import com.kucoin.universal.sdk.model.UnifiedWsMessage;
import java.util.concurrent.CompletableFuture;

public class UnifiedPrivateWsImpl implements UnifiedPrivateWs {
  private final WebSocketUnifiedService wsService;

  public UnifiedPrivateWsImpl(WebSocketUnifiedService wsService) {
    this.wsService = wsService;
  }

  @Override
  public CompletableFuture<UnifiedWsMessage> unifiedTrading(UnifiedWsArgs args) {
    return wsService.call(args);
  }

  public void start() {
    this.wsService.start();
  }

  public void stop() {
    this.wsService.stop();
  }
}
