// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.unified.unifiedws;

import com.kucoin.universal.sdk.model.UnifiedWsArgs;
import com.kucoin.universal.sdk.model.UnifiedWsMessage;
import java.util.concurrent.CompletableFuture;

public interface UnifiedPrivateWs {
  /**
   * Unified Websocket Trading API
   *
   * <p>Place spot, margin, or futures orders via a secure WebSocket connection. Supports real-time
   * submission with instant server response.
   *
   * @return A CompletableFuture that completes with the response of the request when the operation
   *     is successful
   * @see <a href="https://www.kucoin.com/docs-new/3470133w0">docs</a>
   */
  CompletableFuture<UnifiedWsMessage> unifiedTrading(UnifiedWsArgs args);

  /**
   * Initiates the WebSocket service
   *
   * <p>This method must be called before invoke any apis.
   */
  void start();

  /**
   * Stops the WebSocket service.
   *
   * <p>This method is used to terminate the WebSocket connection and stop all ongoing calls. It
   * should be called when no further communication is needed with the server, or when the
   * application is being shut down to ensure a clean disconnection and release of resources.
   */
  void stop();
}
