// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.viplending;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAccountsData {
    /**
    * UID
    */
    @JsonProperty("uid")
    private String uid;

    /**
    * Margin Currency
    */
    @JsonProperty("marginCcy")
    private String marginCcy;

    /**
    * Maintenance Quantity (Calculated with Margin Coefficient)
    */
    @JsonProperty("marginQty")
    private String marginQty;

    /**
    * Margin Coefficient
    */
    @JsonProperty("marginFactor")
    private String marginFactor;

    /**
    * Account Type
    */
    @JsonProperty("accountType")
    private AccountTypeEnum accountType;

    /**
    * If It Is Master Account
    */
    @JsonProperty("isParent")
    private Boolean isParent;



    public enum AccountTypeEnum {
        /**
        * 
        */
        UNIFIED("UNIFIED");

        private final String value;

        AccountTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static AccountTypeEnum fromValue(String value) {
          for (AccountTypeEnum b :  AccountTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
