// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.viplending;
import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class VIPLendingApiImpl implements VIPLendingApi {
    private final Transport transport;

    public VIPLendingApiImpl(Transport transport)
    {
        this.transport = transport;
    }

    public  GetAccountsResp getAccounts(GetAccountsReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/otc-loan/account", req, GetAccountsResp.class, false);
    }

    public  GetDiscountRateConfigsResp getDiscountRateConfigs(GetDiscountRateConfigsReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/otc-loan/discount-rate", req, GetDiscountRateConfigsResp.class, false);
    }

    public  GetLoanInfoResp getLoanInfo(GetLoanInfoReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/otc-loan/loan", req, GetLoanInfoResp.class, false);
    }

}