// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.viplending;

public interface VIPLendingApi {
    /**
    * Get Accounts
    *
    * <p>:::info[Description] Accounts participating in OTC lending. This interface is only for querying accounts currently running OTC lending. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetAccountsResp getAccounts(GetAccountsReq req);

    /**
    * Get Collateral Ratio
    *
    * <p>:::info[Description] Get the gradient collateral rate of each currency :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 10
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetDiscountRateConfigsResp getDiscountRateConfigs(GetDiscountRateConfigsReq req);

    /**
    * Get Loan Info
    *
    * <p>:::info[Description] The following information is only applicable to loans.  Get information on off-exchange funding and loans. This endpoint is only for querying accounts that are currently involved in loans. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetLoanInfoResp getLoanInfo(GetLoanInfoReq req);

}