// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { UnifiedWsArgs, UnifiedWsMessage } from '@model/unified_ws';
import { DefaultWebSocketUnifiedService } from '@internal/infra/default_ws_unified_service';

export interface UnifiedPrivateWS {
    /**
     * Unified Websocket Trading API
     * Place spot, margin, or futures orders via a secure WebSocket connection.
     * @see https://www.kucoin.com/docs-new/3470133w0
     */
    unifiedTrading(args: UnifiedWsArgs): Promise<UnifiedWsMessage>;

    /** Start websocket */
    start(): Promise<void> | void;
    /** Stop websocket */
    stop(): Promise<void> | void;
}

export class UnifiedPrivateWSImpl implements UnifiedPrivateWS {
    private wsService: DefaultWebSocketUnifiedService;

    constructor(wsService: DefaultWebSocketUnifiedService) {
        this.wsService = wsService;
    }

    unifiedTrading(args: UnifiedWsArgs): Promise<UnifiedWsMessage> {
        return this.wsService.call(args);
    }

    start(): Promise<void> | void {
        return this.wsService.start();
    }

    stop(): Promise<void> | void {
        return this.wsService.stop();
    }
}