// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class AmendOrderResp implements Response<AmendOrderResp, RestResponse<AmendOrderResp>> {
    /**
    * Order ID. Note: Returning orderID indicates success. The final result of changing the order will be pushed through websocket.
    */
    @JsonProperty("orderId")
    private String orderId;

    /**
    * Client Order ID. Note: Returning Client Order ID indicates success. The final result of changing the order will be pushed through websocket.
    */
    @JsonProperty("clientOid")
    private String clientOid;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<AmendOrderResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<AmendOrderResp> response) {
        this.commonResponse = response;
    }



}
