// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class BatchCancelOrdersByIdItems {
    /**
    * 
    */
    @JsonProperty("code")
    private String code;

    /**
    * 
    */
    @JsonProperty("msg")
    private String msg;

    /**
    * Order ID
    */
    @JsonProperty("orderId")
    private String orderId;

    /**
    * User-defined order ID
    */
    @JsonProperty("clientOid")
    private String clientOid;

    /**
    * Timestamp when the system completes the order cancellation request.
    */
    @JsonProperty("ts")
    private Long ts;



}
