// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class CancelOrderReq implements Request {
    /**
    * Trade Type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Trading pair.  - For FUTURES, symbol is optional for single order cancellation and is ignored if orderId is provided.  - For unified accounts with FUTURES, symbol is required.
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Order ID. At least one of orderId or clientOid must be provided. If both are provided, orderId takes precedence.
    */
    @JsonProperty("orderId")
    private String orderId;

    /**
    * User-defined order ID. At least one of orderId or clientOid must be provided. If both are provided, orderId takes precedence.
    */
    @JsonProperty("clientOid")
    private String clientOid;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        MARGIN("MARGIN");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
