// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOrderHistoryReq implements Request {
    /**
    * Trade Type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Trading pair name.   
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Trade direction
    */
    @JsonProperty("side")
    private SideEnum side;

    /**
    * Order type filter
    */
    @JsonProperty("orderFilter")
    @Builder.Default
    private OrderFilterEnum orderFilter = OrderFilterEnum.NORMAL;

    /**
    * Start time (milliseconds). If no time range is specified, defaults to returning orders from the last 7 days. 
    */
    @JsonProperty("startAt")
    private String startAt;

    /**
    * End time (milliseconds). If no time range is specified, defaults to returning orders from the last 7 days. 
    */
    @JsonProperty("endAt")
    private String endAt;

    /**
    * ID of the last record from the previous request. 
    */
    @JsonProperty("lastId")
    private Long lastId;

    /**
    * Number of orders per page. 
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 50L;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        MARGIN("MARGIN");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SideEnum {
        /**
        * 
        */
        BUY("BUY"),
        /**
        * 
        */
        SELL("SELL");

        private final String value;

        SideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SideEnum fromValue(String value) {
          for (SideEnum b :  SideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum OrderFilterEnum {
        /**
        * 
        */
        NORMAL("NORMAL"),
        /**
        * 
        */
        ADVANCED("ADVANCED");

        private final String value;

        OrderFilterEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static OrderFilterEnum fromValue(String value) {
          for (OrderFilterEnum b :  OrderFilterEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
