// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOrderDetailsResp implements Response<GetOrderDetailsResp, RestResponse<GetOrderDetailsResp>> {
    /**
    * - SPOT (Spot) - FUTURES (Futures) - MARGIN (Margin)
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Order ID
    */
    @JsonProperty("orderId")
    private String orderId;

    /**
    * User-defined order ID. For unified accounts, conditional orders for SPOT and FUTURES do not inherit clientOid.
    */
    @JsonProperty("clientOid")
    private String clientOid;

    /**
    * Order status | Code | Status | Merged Definition | |---|---|---| | 0 | notTriggered | Conditional order only; not triggered. Supported by FUTURES only. | | 1 | triggered | Conditional order triggered. Classic Account: intermediate state between trigger and live. Unified Account: final state after trigger. | | 2 | live | Not filled. | | 3 | filled | Fully filled. | | 4 | partial filled | Partially filled, still active. | | 5 | canceled | No fills, fully canceled. | | 6 | partial canceled | Partially filled, remainder canceled. |  Note: SPOT supports codes 2–6; FUTURES supports codes 0 and 2–6; ISOLATED/CROSS supports codes 2–6.
    */
    @JsonProperty("status")
    private StatusEnum status;

    /**
    * Cumulative filled quantity of the order
    */
    @JsonProperty("filledSize")
    private String filledSize;

    /**
    * Average filled price of the order. For FUTURES, rounded to tickSize precision.
    */
    @JsonProperty("avgPrice")
    private String avgPrice;

    /**
    * Cumulative order fee
    */
    @JsonProperty("fee")
    private String fee;

    /**
    * Currency of the order fee
    */
    @JsonProperty("feeCurrency")
    private String feeCurrency;

    /**
    * Settled tax fee for the order
    */
    @JsonProperty("tax")
    private String tax;

    /**
    * ID of the last trade for the order. May be unavailable if the last trade is older than 7 days for SPOT.
    */
    @JsonProperty("tradeId")
    private String tradeId;

    /**
    * Trading pair name
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Trade direction: BUY or SELL
    */
    @JsonProperty("side")
    private SideEnum side;

    /**
    * Position direction:  - BOTH: One-way mode. - LONG: Hedge mode, long. - SHORT: Hedge mode, short.  Only supported for FUTURES. UTA Futures currently supports one-way mode only.
    */
    @JsonProperty("positionSide")
    private PositionSideEnum positionSide;

    /**
    * Order type: LIMIT or MARKET
    */
    @JsonProperty("orderType")
    private OrderTypeEnum orderType;

    /**
    * Order quantity
    */
    @JsonProperty("size")
    private String size;

    /**
    * Order quantity unit:  - BASECCY: Base currency - QUOTECCY: Quote currency - UNIT: Contract units (only supported for FUTURES, returns UNIT)
    */
    @JsonProperty("sizeUnit")
    private SizeUnitEnum sizeUnit;

    /**
    * Order price. Only valid for LIMIT orders; returns empty string for other order types.
    */
    @JsonProperty("price")
    private String price;

    /**
    * Whether the order is reduce-only. True or False, defaults to False. Only applies to FUTURES; returns empty string for other types.
    */
    @JsonProperty("reduceOnly")
    private Boolean reduceOnly;

    /**
    * - ISOLATED: Isolated margin - CROSS: Cross margin. 
    */
    @JsonProperty("marginMode")
    private MarginModeEnum marginMode;

    /**
    * Self-Trade Prevention Mode, default off.
    */
    @JsonProperty("stp")
    private StpEnum stp;

    /**
    * [Time in Force](apidog://link/pages/338146) is a special strategy used during trading to specify how long an order remains active before execution or expiration. Market orders are not supported. Order fills include self-fills. Default is GTC.
    */
    @JsonProperty("timeInForce")
    private TimeInForceEnum timeInForce;

    /**
    * Reason for order cancellation, `cancelReason` is a `string`. Use the returned string value directly as the cancel reason (do not map it to the integer enum). [Cancel Reason Link](apidog://link/pages/338146)
    */
    @JsonProperty("cancelReason")
    private String cancelReason;

    /**
    * Canceled quantity of the order
    */
    @JsonProperty("cancelSize")
    private String cancelSize;

    /**
    * Cancel order after N seconds. Only applies to GTC orders; returns 0 for other order types. Supported for SPOT and MARGIN orders.
    */
    @JsonProperty("cancelAfter")
    private Long cancelAfter;

    /**
    * Conditional order trigger direction: UP or DOWN. Only applies to FUTURES conditional orders.
    */
    @JsonProperty("triggerDirection")
    private TriggerDirectionEnum triggerDirection;

    /**
    * Conditional order trigger price. Only applies to FUTURES conditional orders.
    */
    @JsonProperty("triggerPrice")
    private String triggerPrice;

    /**
    * Conditional order trigger price type:  - TP: Transaction price (default) - IP: Index price - MP: Mark price.  Only applies to FUTURES conditional orders.
    */
    @JsonProperty("triggerPriceType")
    private TriggerPriceTypeEnum triggerPriceType;

    /**
    * Take-profit trigger price. Only applies to FUTURES conditional orders.
    */
    @JsonProperty("tpTriggerPrice")
    private String tpTriggerPrice;

    /**
    * Take-profit trigger price type:  - TP: Transaction price (default) - IP: Index price - MP: Mark price.  Only applies to FUTURES conditional orders.
    */
    @JsonProperty("tpTriggerPriceType")
    private TpTriggerPriceTypeEnum tpTriggerPriceType;

    /**
    * Take-profit order execution price. If empty, executes at market price. Currently not supported as only market orders are allowed for FUTURES.
    */
    @JsonProperty("tpOrderPrice")
    private String tpOrderPrice;

    /**
    * Stop-loss trigger price. Only applies to FUTURES conditional orders.
    */
    @JsonProperty("slTriggerPrice")
    private String slTriggerPrice;

    /**
    * Stop-loss trigger price type:  - TP: Transaction price (default) - IP: Index price - MP: Mark price.  Only applies to FUTURES conditional orders.
    */
    @JsonProperty("slTriggerPriceType")
    private SlTriggerPriceTypeEnum slTriggerPriceType;

    /**
    * Stop-loss order execution price. If empty, executes at market price. Currently not supported as only market orders are allowed for FUTURES.
    */
    @JsonProperty("slOrderPrice")
    private String slOrderPrice;

    /**
    * Whether the order is post-only. Invalid when timeInForce is IOC.
    */
    @JsonProperty("postOnly")
    private Boolean postOnly;

    /**
    * Order description or tags.
    */
    @JsonProperty("tags")
    private String tags;

    /**
    * Original conditional order ID for orders triggered by conditional orders.
    */
    @JsonProperty("triggerOrderId")
    private String triggerOrderId;

    /**
    * Order creation time, in nanoseconds.
    */
    @JsonProperty("orderTime")
    private Long orderTime;

    /**
    * Latest order update time, in nanoseconds.
    */
    @JsonProperty("updatedTime")
    private Long updatedTime;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetOrderDetailsResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetOrderDetailsResp> response) {
        this.commonResponse = response;
    }



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        MARGIN("MARGIN");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum StatusEnum {
        /**
        * 
        */
        _0(0),
        /**
        * 
        */
        _1(1),
        /**
        * 
        */
        _2(2),
        /**
        * 
        */
        _3(3),
        /**
        * 
        */
        _4(4),
        /**
        * 
        */
        _5(5),
        /**
        * 
        */
        _6(6);

        private final Integer value;

        StatusEnum(Integer value) {
            this.value = value;
        }

        @JsonValue
        public Integer getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(Integer value) {
          for (StatusEnum b :  StatusEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SideEnum {
        /**
        * 
        */
        BUY("BUY"),
        /**
        * 
        */
        SELL("SELL");

        private final String value;

        SideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SideEnum fromValue(String value) {
          for (SideEnum b :  SideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum PositionSideEnum {
        /**
        * 
        */
        BOTH("BOTH"),
        /**
        * 
        */
        LONG("LONG"),
        /**
        * 
        */
        SHORT("SHORT");

        private final String value;

        PositionSideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static PositionSideEnum fromValue(String value) {
          for (PositionSideEnum b :  PositionSideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum OrderTypeEnum {
        /**
        * 
        */
        LIMIT("LIMIT"),
        /**
        * 
        */
        MARKET("MARKET");

        private final String value;

        OrderTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static OrderTypeEnum fromValue(String value) {
          for (OrderTypeEnum b :  OrderTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SizeUnitEnum {
        /**
        * 
        */
        BASECCY("BASECCY"),
        /**
        * 
        */
        QUOTECCY("QUOTECCY"),
        /**
        * 
        */
        UNIT("UNIT");

        private final String value;

        SizeUnitEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SizeUnitEnum fromValue(String value) {
          for (SizeUnitEnum b :  SizeUnitEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum MarginModeEnum {
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        CROSS("CROSS"),

        NULL("");

        private final String value;

        MarginModeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static MarginModeEnum fromValue(String value) {
          for (MarginModeEnum b :  MarginModeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum StpEnum {
        /**
        * 
        */
        DC("DC"),
        /**
        * 
        */
        CO("CO"),
        /**
        * 
        */
        CN("CN"),
        /**
        * 
        */
        CB("CB"),

        NULL("");

        private final String value;

        StpEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static StpEnum fromValue(String value) {
          for (StpEnum b :  StpEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TimeInForceEnum {
        /**
        * 
        */
        GTC("GTC"),
        /**
        * 
        */
        IOC("IOC"),
        /**
        * 
        */
        GTT("GTT"),
        /**
        * 
        */
        FOK("FOK"),
        /**
        * 
        */
        RPI("RPI");

        private final String value;

        TimeInForceEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TimeInForceEnum fromValue(String value) {
          for (TimeInForceEnum b :  TimeInForceEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TriggerDirectionEnum {
        /**
        * 
        */
        UP("UP"),
        /**
        * 
        */
        DOWN("DOWN"),

        NULL("");

        private final String value;

        TriggerDirectionEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TriggerDirectionEnum fromValue(String value) {
          for (TriggerDirectionEnum b :  TriggerDirectionEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TriggerPriceTypeEnum {
        /**
        * 
        */
        TP("TP"),
        /**
        * 
        */
        IP("IP"),
        /**
        * 
        */
        MP("MP"),

        NULL("");

        private final String value;

        TriggerPriceTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TriggerPriceTypeEnum fromValue(String value) {
          for (TriggerPriceTypeEnum b :  TriggerPriceTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TpTriggerPriceTypeEnum {
        /**
        * 
        */
        TP("TP"),
        /**
        * 
        */
        IP("IP"),
        /**
        * 
        */
        MP("MP"),

        NULL("");

        private final String value;

        TpTriggerPriceTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TpTriggerPriceTypeEnum fromValue(String value) {
          for (TpTriggerPriceTypeEnum b :  TpTriggerPriceTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SlTriggerPriceTypeEnum {
        /**
        * 
        */
        TP("TP"),
        /**
        * 
        */
        IP("IP"),
        /**
        * 
        */
        MP("MP"),

        NULL("");

        private final String value;

        SlTriggerPriceTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SlTriggerPriceTypeEnum fromValue(String value) {
          for (SlTriggerPriceTypeEnum b :  SlTriggerPriceTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
