// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOpenOrderListReq implements Request {
    /**
    * Trade Type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Trading pair name. 
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Order type filter, If not provided, it defaults to NORMAL orders
    */
    @JsonProperty("orderFilter")
    @Builder.Default
    private OrderFilterEnum orderFilter = OrderFilterEnum.NORMAL;

    /**
    * Current page number
    */
    @JsonProperty("pageNumber")
    @Builder.Default
    private String pageNumber = "1";

    /**
    * Number of order items returned per page
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private String pageSize = "50";



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        MARGIN("MARGIN");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum OrderFilterEnum {
        /**
        * 
        */
        NORMAL("NORMAL"),
        /**
        * 
        */
        ADVANCED("ADVANCED");

        private final String value;

        OrderFilterEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static OrderFilterEnum fromValue(String value) {
          for (OrderFilterEnum b :  OrderFilterEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
