// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTradeHistoryReq implements Request {
    /**
    * Trade type.
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Trading pair name.
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Order ID.
    */
    @JsonProperty("orderId")
    private String orderId;

    /**
    * Trade direction: BUY, SELL.
    */
    @JsonProperty("side")
    private SideEnum side;

    /**
    * Start time (milliseconds). If no time range is specified, defaults to returning orders from the last 7 days.
    */
    @JsonProperty("startAt")
    private String startAt;

    /**
    * End time (milliseconds). If no time range is specified, defaults to returning orders from the last 7 days.
    */
    @JsonProperty("endAt")
    private String endAt;

    /**
    * ID of the last record from the previous request.
    */
    @JsonProperty("lastId")
    private String lastId;

    /**
    * Number of orders per page. Default: 50, Maximum: 200.
    */
    @JsonProperty("pageSize")
    private Long pageSize;

    /**
    * Fill type.
    */
    @JsonProperty("fillType")
    private FillTypeEnum fillType;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        MARGIN("MARGIN");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SideEnum {
        /**
        * 
        */
        BUY("BUY"),
        /**
        * 
        */
        SELL("SELL");

        private final String value;

        SideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SideEnum fromValue(String value) {
          for (SideEnum b :  SideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum FillTypeEnum {
        /**
        * 
        */
        NORMAL("NORMAL"),
        /**
        * 
        */
        ADL("ADL"),
        /**
        * 
        */
        LIQUID("LIQUID"),
        /**
        * 
        */
        SETTLEMENT("SETTLEMENT"),
        /**
        * 
        */
        RECONCILIATION("RECONCILIATION");

        private final String value;

        FillTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static FillTypeEnum fromValue(String value) {
          for (FillTypeEnum b :  FillTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
