// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTradeHistoryItems {
    /**
    * Trading pair name
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Order ID
    */
    @JsonProperty("orderId")
    private String orderId;

    /**
    * Order type: - LIMIT: Limit order - MARKET: Market order
    */
    @JsonProperty("orderType")
    private OrderTypeEnum orderType;

    /**
    * Trade direction: BUY or SELL
    */
    @JsonProperty("side")
    private SideEnum side;

    /**
    * Position direction:  - BOTH: One-way mode. - LONG: Hedge mode, long. - SHORT: Hedge mode, short.  Only supported for FUTURES. UTA Futures currently supports one-way mode only.
    */
    @JsonProperty("positionSide")
    private PositionSideEnum positionSide;

    /**
    * Fill type
    */
    @JsonProperty("fillType")
    private FillTypeEnum fillType;

    /**
    * ID of the current trade for the order
    */
    @JsonProperty("tradeId")
    private String tradeId;

    /**
    * Trade quantity
    */
    @JsonProperty("size")
    private String size;

    /**
    * Trade value
    */
    @JsonProperty("value")
    private String value;

    /**
    * Trade price
    */
    @JsonProperty("price")
    private String price;

    /**
    * Trade execution time, in nanoseconds
    */
    @JsonProperty("executionTime")
    private Long executionTime;

    /**
    * Trade fee
    */
    @JsonProperty("fee")
    private String fee;

    /**
    * Currency of the trade fee
    */
    @JsonProperty("feeCurrency")
    private String feeCurrency;

    /**
    * Liquidity type: MAKER or TAKER
    */
    @JsonProperty("liquidityRole")
    private LiquidityRoleEnum liquidityRole;

    /**
    * Margin mode: - ISOLATED: Isolated margin - CROSS: Cross margin
    */
    @JsonProperty("marginMode")
    private MarginModeEnum marginMode;

    /**
    * Settled tax fee for the trade
    */
    @JsonProperty("tax")
    private String tax;



    public enum OrderTypeEnum {
        /**
        * 
        */
        LIMIT("LIMIT"),
        /**
        * 
        */
        MARKET("MARKET");

        private final String value;

        OrderTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static OrderTypeEnum fromValue(String value) {
          for (OrderTypeEnum b :  OrderTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SideEnum {
        /**
        * 
        */
        BUY("BUY"),
        /**
        * 
        */
        SELL("SELL");

        private final String value;

        SideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SideEnum fromValue(String value) {
          for (SideEnum b :  SideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum PositionSideEnum {
        /**
        * 
        */
        BOTH("BOTH"),
        /**
        * 
        */
        LONG("LONG"),
        /**
        * 
        */
        SHORT("SHORT");

        private final String value;

        PositionSideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static PositionSideEnum fromValue(String value) {
          for (PositionSideEnum b :  PositionSideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum FillTypeEnum {
        /**
        * 
        */
        NORMAL("NORMAL"),
        /**
        * 
        */
        LIQUID("LIQUID"),
        /**
        * 
        */
        ADL("ADL"),
        /**
        * 
        */
        SETTLEMENT("SETTLEMENT"),
        /**
        * 
        */
        RECONCILIATION("RECONCILIATION");

        private final String value;

        FillTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static FillTypeEnum fromValue(String value) {
          for (FillTypeEnum b :  FillTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum LiquidityRoleEnum {
        /**
        * 
        */
        MAKER("MAKER"),
        /**
        * 
        */
        TAKER("TAKER");

        private final String value;

        LiquidityRoleEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static LiquidityRoleEnum fromValue(String value) {
          for (LiquidityRoleEnum b :  LiquidityRoleEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum MarginModeEnum {
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        CROSS("CROSS");

        private final String value;

        MarginModeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static MarginModeEnum fromValue(String value) {
          for (MarginModeEnum b :  MarginModeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
