// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;
import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class OrderApiImpl implements OrderApi {
    private final Transport transport;

    public OrderApiImpl(Transport transport)
    {
        this.transport = transport;
    }

    public  BatchCancelOrdersBySymbolResp batchCancelOrdersBySymbol(BatchCancelOrdersBySymbolReq req){
        return this.transport.call("spot", false, "POST", "/api/ua/v2/unified/order/cancel-all", req, BatchCancelOrdersBySymbolResp.class, false);
    }

    public  BatchCancelOrdersByIdResp batchCancelOrdersById(BatchCancelOrdersByIdReq req){
        return this.transport.call("spot", false, "POST", "/api/ua/v2/unified/order/cancel-batch", req, BatchCancelOrdersByIdResp.class, false);
    }

    public  CancelOrderResp cancelOrder(CancelOrderReq req){
        return this.transport.call("spot", false, "POST", "/api/ua/v2/unified/order/cancel", req, CancelOrderResp.class, false);
    }

    public  GetOrderDetailsResp getOrderDetails(GetOrderDetailsReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/unified/order/detail", req, GetOrderDetailsResp.class, false);
    }

    public  GetTradeHistoryResp getTradeHistory(GetTradeHistoryReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/unified/order/execution", req, GetTradeHistoryResp.class, false);
    }

    public  GetOrderHistoryResp getOrderHistory(GetOrderHistoryReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/unified/order/history", req, GetOrderHistoryResp.class, false);
    }

    public  GetOpenOrderListResp getOpenOrderList(GetOpenOrderListReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/unified/order/open-list", req, GetOpenOrderListResp.class, false);
    }

    public  PlaceOrderResp placeOrder(PlaceOrderReq req){
        return this.transport.call("spot", false, "POST", "/api/ua/v2/unified/order/place", req, PlaceOrderResp.class, false);
    }

    public  AmendOrderResp amendOrder(AmendOrderReq req){
        return this.transport.call("spot", false, "POST", "/api/ua/v2/unified/order/amend", req, AmendOrderResp.class, false);
    }

}