// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

public interface OrderApi {
    /**
    * Batch Cancel Orders By Symbol
    *
    * <p>:::info[Description] This endpoint cancels orders in batch by symbol.  1. Each request supports up to **100** orders. 2. Currently supported account type: **Unified Trading Account (UTA)** only. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : UNIFIED
    * <li>API-RATE-LIMIT-POOL    : UNIFIED ACCOUNT
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    BatchCancelOrdersBySymbolResp batchCancelOrdersBySymbol(BatchCancelOrdersBySymbolReq req);

    /**
    * Batch Cancel Orders By ID
    *
    * <p>:::info[Description] This interface can be used for batch cancel orders by OrderIds/ClientOrderIds ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : UNIFIED
    * <li>API-RATE-LIMIT-POOL    : UNIFIED ACCOUNT
    * <li>API-RATE-LIMIT-WEIGHT  : 4
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    BatchCancelOrdersByIdResp batchCancelOrdersById(BatchCancelOrdersByIdReq req);

    /**
    * Cancel Order
    *
    * <p>:::info[Description] This interface can be used for cancel orders ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : UNIFIED
    * <li>API-RATE-LIMIT-POOL    : UNIFIED ACCOUNT
    * <li>API-RATE-LIMIT-WEIGHT  : 1
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    CancelOrderResp cancelOrder(CancelOrderReq req);

    /**
    * Get Order Details 
    *
    * <p>:::info[Description] This interface can be used getting single order details. :::   :::tip[Tips] Historical Order Query Limits.  | Order Type | Queryable Time Range | | --- | --- | | Canceled &#x60;NORMAL&#x60; orders without fills | Within the last **2 hours** | | Triggered or canceled &#x60;ADVANCED&#x60; orders | Within the last **2 hours** | | &#x60;NORMAL&#x60; Orders with fills | Within the last **168 hours** |    &gt;**Note** If the specified time range exceeds the allowed window, the system will query data within the corresponding maximum window by default. ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 4
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetOrderDetailsResp getOrderDetails(GetOrderDetailsReq req);

    /**
    * Get Trade History
    *
    * <p>:::info[Description] This interface can be used for getting trade history ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 4
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetTradeHistoryResp getTradeHistory(GetTradeHistoryReq req);

    /**
    * Get Order History
    *
    * <p>:::info[Description] This interface can be used for getting order history :::  :::tip[Tips] Historical Order Query Limits.  | Order Type | Queryable Time Range | | --- | --- | | Canceled &#x60;NORMAL&#x60; orders without fills | Within the last **2 hours** | | Triggered or canceled &#x60;ADVANCED&#x60; orders | Within the last **2 hours** | |&#x60;NORMAL&#x60; Orders with fills | Within the last **168 hours** |    &gt;**Note** If the specified time range exceeds the allowed window, the system will query data within the corresponding maximum window by default. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 4
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetOrderHistoryResp getOrderHistory(GetOrderHistoryReq req);

    /**
    * Get Open Order List
    *
    * <p>:::info[Description] This interface can be used getting open order list, Sort by &#39;orderTime&#39; in descending order ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 4
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetOpenOrderListResp getOpenOrderList(GetOpenOrderListReq req);

    /**
    * Place Order
    *
    * <p>:::info[Description] This interface can be used to place orders. :::  :::tip[Tips] **Active Order Quotas**  | Account Mode | Trade Type | Dimension | Cap | | --- | --- | --- | ---: | | UTA | SPOT&lt;br&gt;FUTURES&lt;br&gt;MARGIN| Active orders per UID | 3000 | | UTA | SPOT&lt;br&gt;FUTURES&lt;br&gt;MARGIN | Active orders per trading pair | 500 |  &gt; **Notes** &gt; 1. Master account UID and Sub-account UID have independent quotas (counted per UID). &gt; 2. UTA quotas are independent from Classic Account quotas. &gt; 3. Quota refresh: real-time. &gt; 4. “Stop Order” is renamed to “Conditional Order” in the latest interfaces. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : UNIFIED
    * <li>API-RATE-LIMIT-POOL    : UNIFIED ACCOUNT
    * <li>API-RATE-LIMIT-WEIGHT  : 1
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    PlaceOrderResp placeOrder(PlaceOrderReq req);

    /**
    * Amend Order
    *
    * <p>Modify an existing order. Supports modifying price, size, and TP/SL trigger prices. Either orderId or clientOid must be provided. (Currently only futures are supported). 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : UNIFIED
    * <li>API-RATE-LIMIT-POOL    : UNIFIED ACCOUNT
    * <li>API-RATE-LIMIT-WEIGHT  : 2
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    AmendOrderResp amendOrder(AmendOrderReq req);

}