// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class PlaceOrderReq implements Request {
    /**
    * Trade Type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Custom Order ID, the maximum length cannot exceed 40, e.g. UUID only allows numbers, characters, underline(_), and separator (-).
    */
    @JsonProperty("clientOid")
    private String clientOid;

    /**
    * Trading Pair
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Conditional Orders supported; `triggerDirection`, `triggerPrice`, `triggerPriceType` effective.<br>Required when `triggerPrice` is provided.<br>`DOWN` = triggers on downward cross<br>`UP` = triggers on upward cross<br>Cannot be used with TP SL in the same order.
    */
    @JsonProperty("triggerDirection")
    private TriggerDirectionEnum triggerDirection;

    /**
    * Trigger Price Type  Only effective for Futures;  Spot/Margin defaults to be \"TP\" 
    */
    @JsonProperty("triggerPriceType")
    private TriggerPriceTypeEnum triggerPriceType;

    /**
    * Trigger Price for Conditional Order, required when triggerDirection is set
    */
    @JsonProperty("triggerPrice")
    private String triggerPrice;

    /**
    * Trade Direction
    */
    @JsonProperty("side")
    private SideEnum side;

    /**
    * Order Type
    */
    @JsonProperty("orderType")
    private OrderTypeEnum orderType;

    /**
    * | Trade Type | Description | | --- | --- | | SPOT | `size` required. Unit controlled by `sizeUnit`.Market Order:`BASECCY` (default) or `QUOTECCY`.Limit Order:`BASECCY` only (`QUOTECCY` or empty not allowed). | | FUTURES | `size` uses `UNIT` (contracts).Minimum `size` depends on `sizeUnit`:`BASECCY` → refer to `unitSize` from [Get Symbol](apidog://link/endpoint/3473247)`UNIT` → refer to `lotSize` from [Get Symbol](apidog://link/endpoint/3473247) |
    */
    @JsonProperty("size")
    private String size;

    /**
    * | Trade Type | Description | | --- | --- | | SPOT | Market Order:Required; `BASECCY` (default) or `QUOTECCY`.Limit Order:Required; `BASECCY` only (`QUOTECCY` or empty not allowed). | | FUTURES | Required; `BASECCY` or `UNIT`.If omitted, the request will be rejected. |
    */
    @JsonProperty("sizeUnit")
    private SizeUnitEnum sizeUnit;

    /**
    * Order Price
    */
    @JsonProperty("price")
    private String price;

    /**
    * [TimeInForce](apidog://link/pages/338372), only for Limit Orders
    */
    @JsonProperty("timeInForce")
    @Builder.Default
    private TimeInForceEnum timeInForce = TimeInForceEnum.GTC;

    /**
    * Post Only Flag, No Taker, prioritize IOC and FOK; With Taker, postOnly > stp > timeInForce
    */
    @JsonProperty("postOnly")
    @Builder.Default
    private Boolean postOnly = false;

    /**
    * Reduce Only Order, only for Futures
    */
    @JsonProperty("reduceOnly")
    @Builder.Default
    private Boolean reduceOnly = false;

    /**
    * Self-Trade Prevention Mode, default off 
    */
    @JsonProperty("stp")
    private StpEnum stp;

    /**
    * Order Tags, max length 20
    */
    @JsonProperty("tags")
    private String tags;

    /**
    * Cancel After N Seconds(Calculated from the time of entering the matching engine), only effective when timeInForce is GTT
    */
    @JsonProperty("cancelAfter")
    private Long cancelAfter;

    /**
    * | Account Mode | Trade Type | Description | | --- | --- | --- | | UTA | Not supported | N/A |
    */
    @JsonProperty("positionSide")
    private PositionSideEnum positionSide;

    /**
    * | Account Mode | Trade Type | Description | | --- | --- | --- | | UTA | SPOT |  Not applicable | | UTA | MARGIN | only CROSS supported. Default: CROSS | | UTA | FUTURES | Both CROSS and ISOLATED are supported.  Default: CROSS|
    */
    @JsonProperty("marginMode")
    private MarginModeEnum marginMode;

    /**
    * UTA allows `tpTriggerPriceType` and `slTriggerPriceType` to be different
    */
    @JsonProperty("tpTriggerPriceType")
    @Builder.Default
    private TpTriggerPriceTypeEnum tpTriggerPriceType = TpTriggerPriceTypeEnum.TP;

    /**
    * Take Profit Trigger Price, only for Futures
    */
    @JsonProperty("tpTriggerPrice")
    private String tpTriggerPrice;

    /**
    * UTA allows `tpTriggerPriceType` and `slTriggerPriceType` to be different
    */
    @JsonProperty("slTriggerPriceType")
    @Builder.Default
    private SlTriggerPriceTypeEnum slTriggerPriceType = SlTriggerPriceTypeEnum.TP;

    /**
    * Stop Loss Trigger Price, only for Futures
    */
    @JsonProperty("slTriggerPrice")
    private String slTriggerPrice;

    /**
    * Close position for specified symbol. Once closeOrder is set true, param 'side' and 'size' will be ignored and all pending orders for closing out will be cancelled as well. 
    */
    @JsonProperty("closeOrder")
    @Builder.Default
    private Boolean closeOrder = false;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        MARGIN("MARGIN");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TriggerDirectionEnum {
        /**
        * 
        */
        DOWN("DOWN"),
        /**
        * 
        */
        UP("UP");

        private final String value;

        TriggerDirectionEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TriggerDirectionEnum fromValue(String value) {
          for (TriggerDirectionEnum b :  TriggerDirectionEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TriggerPriceTypeEnum {
        /**
        * 
        */
        TP("TP"),
        /**
        * 
        */
        IP("IP"),
        /**
        * 
        */
        MP("MP");

        private final String value;

        TriggerPriceTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TriggerPriceTypeEnum fromValue(String value) {
          for (TriggerPriceTypeEnum b :  TriggerPriceTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SideEnum {
        /**
        * 
        */
        BUY("BUY"),
        /**
        * 
        */
        SELL("SELL");

        private final String value;

        SideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SideEnum fromValue(String value) {
          for (SideEnum b :  SideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum OrderTypeEnum {
        /**
        * 
        */
        LIMIT("LIMIT"),
        /**
        * 
        */
        MARKET("MARKET");

        private final String value;

        OrderTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static OrderTypeEnum fromValue(String value) {
          for (OrderTypeEnum b :  OrderTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SizeUnitEnum {
        /**
        * 
        */
        BASECCY("BASECCY"),
        /**
        * 
        */
        QUOTECCY("QUOTECCY"),
        /**
        * 
        */
        UNIT("UNIT");

        private final String value;

        SizeUnitEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SizeUnitEnum fromValue(String value) {
          for (SizeUnitEnum b :  SizeUnitEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TimeInForceEnum {
        /**
        * 
        */
        GTC("GTC"),
        /**
        * 
        */
        IOC("IOC"),
        /**
        * 
        */
        GTT("GTT"),
        /**
        * 
        */
        FOK("FOK"),
        /**
        * 
        */
        RPI("RPI");

        private final String value;

        TimeInForceEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TimeInForceEnum fromValue(String value) {
          for (TimeInForceEnum b :  TimeInForceEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum StpEnum {
        /**
        * 
        */
        DC("DC"),
        /**
        * 
        */
        CO("CO"),
        /**
        * 
        */
        CN("CN"),
        /**
        * 
        */
        CB("CB");

        private final String value;

        StpEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static StpEnum fromValue(String value) {
          for (StpEnum b :  StpEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum PositionSideEnum {
        /**
        * 
        */
        BOTH("BOTH"),
        /**
        * 
        */
        LONG("LONG"),
        /**
        * 
        */
        SHORT("SHORT");

        private final String value;

        PositionSideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static PositionSideEnum fromValue(String value) {
          for (PositionSideEnum b :  PositionSideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum MarginModeEnum {
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        CROSS("CROSS");

        private final String value;

        MarginModeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static MarginModeEnum fromValue(String value) {
          for (MarginModeEnum b :  MarginModeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TpTriggerPriceTypeEnum {
        /**
        * 
        */
        TP("TP"),
        /**
        * 
        */
        IP("IP"),
        /**
        * 
        */
        MP("MP");

        private final String value;

        TpTriggerPriceTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TpTriggerPriceTypeEnum fromValue(String value) {
          for (TpTriggerPriceTypeEnum b :  TpTriggerPriceTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SlTriggerPriceTypeEnum {
        /**
        * 
        */
        TP("TP"),
        /**
        * 
        */
        IP("IP"),
        /**
        * 
        */
        MP("MP");

        private final String value;

        SlTriggerPriceTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SlTriggerPriceTypeEnum fromValue(String value) {
          for (SlTriggerPriceTypeEnum b :  SlTriggerPriceTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
