// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class PlaceOrderResp implements Response<PlaceOrderResp, RestResponse<PlaceOrderResp>> {
    /**
    * Trade Type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Order ID
    */
    @JsonProperty("orderId")
    private String orderId;

    /**
    * Custom Order ID: Mandatory for futures and margin orders; optional otherwise. The maximum length cannot exceed 40, e.g. UUID only allows numbers, characters, underline(_), and separator (-).
    */
    @JsonProperty("clientOid")
    private String clientOid;

    /**
    * Timestamp when the system completes the order request.  Classic mode is not supported
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<PlaceOrderResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<PlaceOrderResp> response) {
        this.commonResponse = response;
    }



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        MARGIN("MARGIN");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
