<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Unified\UnifiedWs;

use KuCoin\UniversalSDK\Model\UnifiedWsArgs;
use KuCoin\UniversalSDK\Model\UnifiedWsMessage;
use React\Promise\PromiseInterface;

/**
 * Interface for the unified private WebSocket API of KuCoin.
 */
interface UnifiedPrivateWs
{
    /**
     * Unified Websocket Trading API
     *
     * Place spot, margin, or futures orders via a secure WebSocket connection. Supports real-time submission with instant server response.
     *
     * @return PromiseInterface<UnifiedWsMessage> A promise that resolves with the response message
     * @see https://www.kucoin.com/docs-new/3470133w0
     */
    public function unifiedTrading(UnifiedWsArgs $args): PromiseInterface;


    /**
     * Initiates the WebSocket service
     *
     * This method must be called before invoking any APIs.
     */
    public function start(): PromiseInterface;

    /**
     * Stops the WebSocket service.
     *
     * This method is used to terminate the WebSocket connection and stop all ongoing
     * calls. It should be called when no further communication is needed with
     * the server, or when the application is being shut down to ensure a clean
     * disconnection and release of resources.
     */
    public function stop(): PromiseInterface;
}