<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Unified\UnifiedWs;

use KuCoin\UniversalSDK\Internal\Interfaces\WebSocketUnifiedService;
use KuCoin\UniversalSDK\Model\UnifiedWsArgs;
use React\Promise\PromiseInterface;

/**
 * Implementation of the UnifiedPrivateWs interface.
 */
class UnifiedPrivateWsImpl implements UnifiedPrivateWs
{
    /**
     * @var WebSocketUnifiedService
     */
    private $wsService;

    /**
     * @param WebSocketUnifiedService $wsService
     */
    public function __construct(WebSocketUnifiedService $wsService)
    {
        $this->wsService = $wsService;
    }


    /**
     * {@inheritdoc}
     */
    public function unifiedTrading(UnifiedWsArgs $args): PromiseInterface
    {
        return $this->wsService->call($args);
    }


    /**
     * {@inheritdoc}
     */
    public function start(): PromiseInterface
    {
        return $this->wsService->start();
    }

    /**
     * {@inheritdoc}
     */
    public function stop(): PromiseInterface
    {
        return $this->wsService->stop();
    }
}