// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.service;

import com.kucoin.universal.sdk.generate.uta.account.AccountApi;
import com.kucoin.universal.sdk.generate.uta.affiliate.AffiliateApi;
import com.kucoin.universal.sdk.generate.uta.market.MarketApi;
import com.kucoin.universal.sdk.generate.uta.order.OrderApi;
import com.kucoin.universal.sdk.generate.uta.positions.PositionsApi;
import com.kucoin.universal.sdk.generate.uta.viplending.VIPLendingApi;



public interface UTAService {

    AccountApi getAccountApi();

    MarketApi getMarketApi();

    VIPLendingApi getVIPLendingApi();

    PositionsApi getPositionsApi();

    OrderApi getOrderApi();

    AffiliateApi getAffiliateApi();
}

