// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.kucoin.universal.sdk.internal.interfaces.Response;

public interface AccountApi {
    /**
    * Get Interest History (UTA)
    *
    * <p>:::info[Description] Request the interest records via this endpoint :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 15
    * </ul>
    *
    */

    GetInterestHistoryResp getInterestHistory(GetInterestHistoryReq req);

    /**
    * Get Borrowing Rates and Limits
    *
    * <p>:::info[Description] Retrieve borrowing rates, limits, and currently reserved borrowing amounts, only supported in UTA mode. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 10
    * </ul>
    *
    */

    GetBorrowingRatesAndLimitsResp getBorrowingRatesAndLimits(GetBorrowingRatesAndLimitsReq req);

    /**
    * Get Account Mode
    *
    * <p>:::info[Description] This interface supports  query the list of unified and classic sub-accounts and current account mode. ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    GetAccountModeResp getAccountMode();

    /**
    * Set Account Mode
    *
    * <p>:::info[Description] This interface supports set account mode to UTA ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    SetAccountModeResp setAccountMode(SetAccountModeReq req);

    /**
    * Get Third-Party Custody Account Currency Limits
    *
    * <p>:::info[Description] Request OES Custody quota via this endpoint. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    */

    GetOESCustodyQuotaResp getOESCustodyQuota(GetOESCustodyQuotaReq req);

    /**
    * Set Sub Account Transfer Permission
    *
    * <p>:::info[Description] This endpoint supports setting whether the specified sub-account needs to open the SUB_TO_SUB transfer permission ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : FLEXTRANSFERS
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    SetSubAccountTransferPermissionResp setSubAccountTransferPermission(SetSubAccountTransferPermissionReq req);

    /**
    * Get Account Currency Assets (UTA)
    *
    * <p>:::info[Description] Retrieves currency-level asset details for a Unified Trading Account (UTA), including balance, hold, equity, available, and liability.  ### Buying Power Notes (UTA)  The response of this endpoint provides **currency-level asset information** and should **not** be used to measure **Futures Buying Power**.  1. **Spot**    - Currency-level available amount:      &#x60;available &#x3D; balance + min(unPnL, 0) - hold&#x60;    - Only unrealized losses (&#x60;unPnL &lt; 0&#x60;) are included in the available amount; unrealized profits are not included.  2. **Futures**    - Futures Buying Power should use &#x60;availableMargin&#x60; from **[Get Account Overview (UTA)](apidog://link/endpoint/3476257)**.    - Currency-level fields from this endpoint (e.g., &#x60;balance&#x60;, &#x60;equity&#x60;, &#x60;available&#x60;) are not used to describe or calculate Futures Buying Power. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    GetAccountResp getAccount();

    /**
    * Get Leverage (UTA)
    *
    * <p>:::info[Description] This interface supports querying leverage of the specified symbol or currency ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : UNIFIED
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 10
    * </ul>
    *
    */

    GetLeverageResp getLeverage(GetLeverageReq req);

    /**
    * Modify Cross Margin Leverage (UTA)
    *
    * <p>:::info[Description] This interface supports modify leverage of the specified currency in cross margin(UTA) ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : UNIFIED
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    */

    ModifyMarginCrossLeverageResp modifyMarginCrossLeverage(ModifyMarginCrossLeverageReq req);

    /**
    * Modify Futures Leverage (UTA)
    *
    * <p>:::info[Description] This interface supports modify leverage of the specified futures symbol ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : UNIFIED
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    */

    ModifyLeverageResp modifyLeverage(ModifyLeverageReq req);

    /**
    * Get Account Overview (UTA)
    *
    * <p>:::info[Description] Get Unified Trading Account (UTA) Overview - Account-level Summary of Funds. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    GetAccountOverviewResp getAccountOverview();

    /**
    * Get Apikey Info
    *
    * <p>:::info[Description] Get the api key information. Use the api key awaiting checking to call the endpoint. Both master and sub user&#39;s api key are applicable. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    GetApikeyInfoResp getApikeyInfo();

    /**
    * Add Sub Account API
    *
    * <p>:::info[Description] This endpoint can be used to create APIs for sub-accounts. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    */

    AddSubAccountApiResp addSubAccountApi(AddSubAccountApiReq req);

    /**
    * Get Fee Rate
    *
    * <p>:::info[Description] This interface is for the trading pair’s actual fee rate. You can inquire about fee rates of 10 trading pairs each time at most. The fee rate of your sub-account is the same as that of the master account. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetFeeRateResp getFeeRate(GetFeeRateReq req);

    /**
    * Modify Sub Account API
    *
    * <p>:::info[Description] This endpoint can be used to modify sub-account APIs. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    ModifySubAccountApiResp modifySubAccountApi(ModifySubAccountApiReq req);

    /**
    * Delete Sub Account API
    *
    * <p>:::info[Description] This endpoint can be used to delete sub-account APIs. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    DeleteSubAccountApiResp deleteSubAccountApi(DeleteSubAccountApiReq req);

    /**
    * Get Sub Account API List
    *
    * <p>:::info[Description] This endpoint returns the API list for a sub-account (excluding ND broker sub-accounts). Requests must be signed with the master account API key. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    */

    GetSubAccountApiListResp getSubAccountApiList(GetSubAccountApiListReq req);

    /**
    * Add Sub Account
    *
    * <p>:::info[Description] This endpoint can be used to create sub-accounts. After creation, the returned &#x60;subName&#x60; can be used to log in to the sub-account. ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 15
    * </ul>
    *
    */

    AddSubAccountResp addSubAccount(AddSubAccountReq req);

    /**
    * Get Account Ledger
    *
    * <p>:::info[Description] Get account ledger records for supported account types. :::  :::tip[Usage] Query asset change records by account type, currency, business type, direction, and time range. The response is documented as a unified paginated structure, with ledger fields listed under &#x60;data.items[]&#x60;. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 2
    * </ul>
    *
    */

    GetAccountLedgerResp getAccountLedger(GetAccountLedgerReq req);

    /**
    * Get Account Currency Assets (Classic)
    *
    * <p>:::info[Description] Get currency-level asset details for Classic account types, including funding, spot, futures, cross margin, and isolated margin accounts. :::  :::tip[Usage] Use this endpoint to display balances, check asset availability, or reconcile account assets before transfers. Different &#x60;accountType&#x60; values can return different account groups and currency fields. :::  :::warning[Important] Use only the account types listed in the request schema. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    GetClassicAccountBalanceResp getClassicAccountBalance(GetClassicAccountBalanceReq req);

    /**
    * Get Deposit Address
    *
    * <p>:::info[Description] Retrieve deposit addresses for a currency. Currency values use uppercase currency codes, such as &#x60;USDT&#x60; or &#x60;BTC&#x60;; chain values use lowercase blockchain network identifiers, such as &#x60;trx&#x60; or &#x60;kcc&#x60;. When both currency and chain are provided, the deposit address for that blockchain network is returned and may be created if it does not already exist. If only currency is provided and no address is available, the returned list is empty. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    GetDepositAddressResp getDepositAddress(GetDepositAddressReq req);

    /**
    * Get Deposit History
    *
    * <p>:::info[Description] Retrieve paginated deposit records, including confirmation progress and additional status information. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 2
    * </ul>
    *
    */

    GetDepositHistoryResp getDepositHistory(GetDepositHistoryReq req);

    /**
    * Get Sub Account Currency Assets
    *
    * <p>:::info[Description] Get currency-level asset details for sub-accounts. :::  :::tip[Usage] Use this endpoint to review balances held by sub-accounts across supported account types. &#x60;subAccountType&#x60; is a string and can be a symbol-like value for isolated margin, such as &#x60;AAVE-USDT&#x60;. :::  :::warning[Important] This endpoint supports &#x60;UNIFIED&#x60; in the returned account type where applicable. Do not restrict &#x60;subAccountType&#x60; to a fixed enum. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    GetSubAccountBalanceResp getSubAccountBalance(GetSubAccountBalanceReq req);

    /**
    * Get Transfer Quotas
    *
    * <p>:::info[Description] Get the transferable amount for a specified account type and currency. :::  :::tip[Usage] Use this endpoint before calling [Flex Transfer](apidog://link/endpoint/3478399) to check how much of a currency can be transferred out of the selected account type. For isolated margin, provide &#x60;symbol&#x60; as the isolated trading pair, such as &#x60;BTC-USDT&#x60;. :::  :::warning[Important] &#x60;transferable&#x60; is the amount currently available for transfer, not necessarily the total account balance. The supported &#x60;accountType&#x60; values for this endpoint include &#x60;UNIFIED&#x60;. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    */

    GetTransferQuotaResp getTransferQuota(GetTransferQuotaReq req);

    /**
    * Get Withdrawal Quotas
    *
    * <p>:::info[Description] Get withdrawal quota, fee, and limit information for a specified currency and chain. :::  :::tip[Usage] Use this endpoint before creating a withdrawal to check whether the chain is withdrawable, the available withdrawal amount, and the applicable fee and amount limits. :::  :::warning[Important] Withdrawal availability and limits are chain-specific. Use the exact &#x60;chain&#x60; value returned by the V2 currency endpoints. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 1
    * </ul>
    *
    */

    GetWithdrawalQuotasResp getWithdrawalQuotas(GetWithdrawalQuotasReq req);

    /**
    * Get Withdrawal History
    *
    * <p>:::info[Description] Retrieve paginated withdrawal records. A manually cancelled withdrawal is returned with &#x60;status&#x60; set to &#x60;FAILURE&#x60; and &#x60;failureReason&#x60; set to &#x60;withdraw.manual.cancel&#x60;. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 2
    * </ul>
    *
    */

    GetWithdrawalHistoryResp getWithdrawalHistory(GetWithdrawalHistoryReq req);

    /**
    * Get All API Rate Limit
    *
    * <p>:::info[Description] Query Unified Trading Account (UTA) API [Rate Limit](apidog://link/pages/338149) for all accounts :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    */

    GetAllRateLimitResp getAllRateLimit();

    /**
    * Get API Rate Limit Cap
    *
    * <p>:::info[Description] Query Unified Trading Account (UTA) API [Rate Limit](apidog://link/pages/338149) cap for parent account :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    GetRateLimitCapResp getRateLimitCap();

    /**
    * Get Sub Account List
    *
    * <p>:::info[Description] This endpoint can be used to get a paginated list of sub-accounts. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 2
    * </ul>
    *
    */

    GetSubAccountListResp getSubAccountList(GetSubAccountListReq req);

    /**
    * Get API Rate Limit
    *
    * <p>:::info[Description] Query Unified Trading Account (UTA) API [Rate Limit](apidog://link/pages/338149) :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetRateLimitResp getRateLimit(GetRateLimitReq req);

    /**
    * Set Sub Accounts API Rate Limit
    *
    * <p>:::info[Description] Set API [Rate Limit](apidog://link/pages/338149) for sub accounts under Unified Trading Account (UTA)  :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 15
    * </ul>
    *
    */

    SetRateLimitResp setRateLimit(SetRateLimitReq req);

    /**
    * Flex Transfer
    *
    * <p>:::info[Description] Transfer assets between account types, or between master and sub-accounts, using a flexible transfer request. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : FLEXTRANSFERS
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 4
    * </ul>
    *
    */

    FlexTransferResp flexTransfer(FlexTransferReq req);

    /**
    * KCS Fee Deduction Management
    *
    * <p>:::info[Description] Enable or disable KCS fee deduction for the account. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : UNIFIED
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    SetKcsFeeDeductionResp setKcsFeeDeduction(SetKcsFeeDeductionReq req);

    /**
    * Cancel Withdrawal
    *
    * <p>:::info[Description] Cancel a withdrawal request when cancellation is still allowed. :::  :::tip[Usage] Use the withdrawal ID returned by the withdrawal request or withdrawal history endpoint to cancel a pending withdrawal. :::  :::warning[Important] A withdrawal can be cancelled only while it is still in a cancellable state. Once processing reaches a later state, cancellation may fail. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : WITHDRAWAL
    * <li>API-RATE-LIMIT-POOL    : UNIFIED ACCOUNT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    CancelWithdrawalResp cancelWithdrawal(CancelWithdrawalReq req);

    /**
    * Withdraw
    *
    * <p>:::info[Description] Submit a withdrawal request for a specified currency, chain, amount, and destination. :::  :::tip[Usage] Before submitting a withdrawal, use [Get Currencies](apidog://link/endpoint/3478404) or [Get Currency](apidog://link/endpoint/3478403) to confirm the chain value, memo/tag requirements, withdrawal precision, and limits. :::  :::warning[Important] This endpoint moves funds. If the withdrawal address whitelist is enabled, the address and blockchain network must match a saved favorite address, and address matching is case-sensitive. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : WITHDRAWAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    WithdrawalV3Resp withdrawalV3(WithdrawalV3Req req);

}
