// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class AddSubAccountResp implements Response<AddSubAccountResp, RestResponse<AddSubAccountResp>> {
    /**
    * Sub account user id
    */
    @JsonProperty("uid")
    private Long uid;

    /**
    * Sub-account name. After creation, this value can be used to log in to the sub-account.
    */
    @JsonProperty("subName")
    private String subName;

    /**
    * Sub account name
    */
    @JsonProperty("remarks")
    private String remarks;

    /**
    * Sub-account access permission. In UTA mode, only `ALL` is returned, meaning all trading types are supported. In Classic mode, possible values are `ALL`, `FUTURES`, and `MARGIN`.
    */
    @JsonProperty("access")
    private AccessEnum access;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<AddSubAccountResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<AddSubAccountResp> response) {
        this.commonResponse = response;
    }



    public enum AccessEnum {
        /**
        * 
        */
        ALL("ALL"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        MARGIN("MARGIN");

        private final String value;

        AccessEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static AccessEnum fromValue(String value) {
          for (AccessEnum b :  AccessEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
