// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class CancelWithdrawalResp implements Response<CancelWithdrawalResp, RestResponse<CancelWithdrawalResp>> {
    /**
    * Withdrawal ID.
    */
    @JsonProperty("withdrawId")
    private String withdrawId;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<CancelWithdrawalResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<CancelWithdrawalResp> response) {
        this.commonResponse = response;
    }



}
