// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class FlexTransferReq implements Request {
    /**
    * Client-generated unique transfer ID.
    */
    @JsonProperty("clientOid")
    private String clientOid;

    /**
    * Transfer type.
    */
    @JsonProperty("transferType")
    private TransferTypeEnum transferType;

    /**
    * Currency code, such as `USDT` or `BTC`.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Transfer amount.
    */
    @JsonProperty("amount")
    private String amount;

    /**
    * Source user UID. Required for transfer types that involve a source sub-account.
    */
    @JsonProperty("fromUid")
    private String fromUid;

    /**
    * Source account type.
    */
    @JsonProperty("fromAccountType")
    private FromAccountTypeEnum fromAccountType;

    /**
    * Source account tag.
    */
    @JsonProperty("fromAccountTag")
    private String fromAccountTag;

    /**
    * Destination user UID. Required for transfer types that involve a destination sub-account.
    */
    @JsonProperty("toUid")
    private String toUid;

    /**
    * Destination account type.
    */
    @JsonProperty("toAccountType")
    private ToAccountTypeEnum toAccountType;

    /**
    * Destination account tag.
    */
    @JsonProperty("toAccountTag")
    private String toAccountTag;



    public enum TransferTypeEnum {
        /**
        * 
        */
        INTERNAL("INTERNAL"),
        /**
        * 
        */
        PARENT_TO_SUB("PARENT_TO_SUB"),
        /**
        * 
        */
        SUB_TO_PARENT("SUB_TO_PARENT"),
        /**
        * 
        */
        SUB_TO_SUB("SUB_TO_SUB");

        private final String value;

        TransferTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TransferTypeEnum fromValue(String value) {
          for (TransferTypeEnum b :  TransferTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum FromAccountTypeEnum {
        /**
        * 
        */
        FUNDING("FUNDING"),
        /**
        * 
        */
        UNIFIED("UNIFIED"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        SPOT("SPOT");

        private final String value;

        FromAccountTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static FromAccountTypeEnum fromValue(String value) {
          for (FromAccountTypeEnum b :  FromAccountTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum ToAccountTypeEnum {
        /**
        * 
        */
        FUNDING("FUNDING"),
        /**
        * 
        */
        UNIFIED("UNIFIED"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        SPOT("SPOT");

        private final String value;

        ToAccountTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static ToAccountTypeEnum fromValue(String value) {
          for (ToAccountTypeEnum b :  ToAccountTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
