// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAccountLedgerItems {
    /**
    * Account type.
    */
    @JsonProperty("accountType")
    private AccountTypeEnum accountType;

    /**
    * Ledger record ID.
    */
    @JsonProperty("id")
    private String id;

    /**
    * Currency code, such as `USDT` or `BTC`.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Funds movement direction.
    */
    @JsonProperty("direction")
    private String direction;

    /**
    * Business type of the ledger record.
    */
    @JsonProperty("businessType")
    private String businessType;

    /**
    * Changed amount.
    */
    @JsonProperty("amount")
    private String amount;

    /**
    * Balance after the change, when returned by the underlying account ledger source.
    */
    @JsonProperty("balance")
    private String balance;

    /**
    * Fee amount.
    */
    @JsonProperty("fee")
    private String fee;

    /**
    * Tax amount, when returned by the underlying account ledger source.
    */
    @JsonProperty("tax")
    private String tax;

    /**
    * Remark.
    */
    @JsonProperty("remark")
    private String remark;

    /**
    * Timestamp in milliseconds.
    */
    @JsonProperty("ts")
    private Long ts;



    public enum AccountTypeEnum {
        /**
        * 
        */
        FUNDING("FUNDING"),
        /**
        * 
        */
        UNIFIED("UNIFIED"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        SPOT("SPOT");

        private final String value;

        AccountTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static AccountTypeEnum fromValue(String value) {
          for (AccountTypeEnum b :  AccountTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
