// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetApikeyInfoResp implements Response<GetApikeyInfoResp, RestResponse<GetApikeyInfoResp>> {
    /**
    * Account UID
    */
    @JsonProperty("uid")
    private Long uid;

    /**
    * Master account UID. Returns empty when called by the master account itself.
    */
    @JsonProperty("parentUid")
    private Long parentUid;

    /**
    * KYC region of the account, returns the two-letter country code. [Get KYC Regions](apidog://link/endpoint/3475561)
    */
    @JsonProperty("region")
    private String region;

    /**
    * KYC status.
    */
    @JsonProperty("kycStatus")
    private KycStatusEnum kycStatus;

    /**
    * Sub-account name (not present for the master account)
    */
    @JsonProperty("subName")
    private String subName;

    /**
    * Remarks
    */
    @JsonProperty("remark")
    private String remark;

    /**
    * API key
    */
    @JsonProperty("apiKey")
    private String apiKey;

    /**
    * API version
    */
    @JsonProperty("apiVersion")
    private Long apiVersion;

    /**
    * [Permissions](apidog://link/pages/338144). Possible values: General, Spot, Margin, Unified, Futures, InnerTransfer, Transfer, Earn
    */
    @JsonProperty("permission")
    private String permission;

    /**
    * IP whitelist (comma-separated list of allowed IPs)
    */
    @JsonProperty("ipWhitelist")
    private String ipWhitelist;

    /**
    * Indicates whether this is the master account
    */
    @JsonProperty("isMaster")
    private Boolean isMaster;

    /**
    * API key creation timestamp (Unix milliseconds)
    */
    @JsonProperty("createdAt")
    private Long createdAt;

    /**
    * API key expiration timestamp (Unix milliseconds). Returns `null` if no expiration is set.
    */
    @JsonProperty("expiredAt")
    private Long expiredAt;

    /**
    * Third-party application name. Returns empty string if not associated with any third-party app.
    */
    @JsonProperty("thirdPartyApp")
    private String thirdPartyApp;

    /**
    * Site type.
    */
    @JsonProperty("siteType")
    private SiteTypeEnum siteType;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetApikeyInfoResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetApikeyInfoResp> response) {
        this.commonResponse = response;
    }



    public enum KycStatusEnum {
        /**
        * 
        */
        _0(0),
        /**
        * 
        */
        _1(1);

        private final Integer value;

        KycStatusEnum(Integer value) {
            this.value = value;
        }

        @JsonValue
        public Integer getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static KycStatusEnum fromValue(Integer value) {
          for (KycStatusEnum b :  KycStatusEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SiteTypeEnum {
        /**
        * 
        */
        GLOBAL("global"),
        /**
        * 
        */
        TURKEY("turkey"),
        /**
        * 
        */
        AUSTRALIA("australia"),
        /**
        * 
        */
        EUROPE("europe"),
        /**
        * 
        */
        THAILAND("thailand");

        private final String value;

        SiteTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SiteTypeEnum fromValue(String value) {
          for (SiteTypeEnum b :  SiteTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
