// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAccountLedgerReq implements Request {
    /**
    * Account type used for queries, transfers, or returned records.
    */
    @JsonProperty("accountType")
    private AccountTypeEnum accountType;

    /**
    * Business type used to filter ledger records.
    */
    @JsonProperty("businessType")
    private BusinessTypeEnum businessType;

    /**
    * Currency code, such as `USDT` or `BTC`. Currency values use uppercase codes. If omitted, records for all currencies are returned.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Ledger direction.
    */
    @JsonProperty("direction")
    private DirectionEnum direction;

    /**
    * Start time of the query time range, in milliseconds.
    */
    @JsonProperty("startAt")
    private Long startAt;

    /**
    * End time of the query time range, in milliseconds.
    */
    @JsonProperty("endAt")
    private Long endAt;

    /**
    * The maximum value of pageSize depends on the selected accountType:  | accountType | pageSize Max | | --- | ---: | | UNIFIED | 200 | | FUNDING | 500 | | SPOT | 200 | | CROSS | 500 | | ISOLATED | 500 | | FUTURES | 100 |
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 10L;

    /**
    * ID of the last record from the previous page. If omitted, the latest records are returned.
    */
    @JsonProperty("lastId")
    private Long lastId;



    public enum AccountTypeEnum {
        /**
        * 
        */
        FUNDING("FUNDING"),
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        UNIFIED("UNIFIED");

        private final String value;

        AccountTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static AccountTypeEnum fromValue(String value) {
          for (AccountTypeEnum b :  AccountTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum BusinessTypeEnum {
        /**
        * 
        */
        TRADE_EXCHANGE("TRADE_EXCHANGE"),
        /**
        * 
        */
        TRANSFER("TRANSFER"),
        /**
        * 
        */
        SUB_TRANSFER("SUB_TRANSFER"),
        /**
        * 
        */
        RETURNED_FEES("RETURNED_FEES"),
        /**
        * 
        */
        DEDUCTION_FEES("DEDUCTION_FEES"),
        /**
        * 
        */
        OTHER("OTHER"),
        /**
        * 
        */
        SUB_TO_SUB_TRANSFER("SUB_TO_SUB_TRANSFER"),
        /**
        * 
        */
        SPOT_EXCHANGE("SPOT_EXCHANGE"),
        /**
        * 
        */
        SPOT_EXCHANGE_REBATE("SPOT_EXCHANGE_REBATE"),
        /**
        * 
        */
        FUTURES_EXCHANGE_OPEN("FUTURES_EXCHANGE_OPEN"),
        /**
        * 
        */
        FUTURES_EXCHANGE_CLOSE("FUTURES_EXCHANGE_CLOSE"),
        /**
        * 
        */
        FUTURES_EXCHANGE_REBATE("FUTURES_EXCHANGE_REBATE"),
        /**
        * 
        */
        FUNDING_FEE("FUNDING_FEE"),
        /**
        * 
        */
        LIABILITY_INTEREST("LIABILITY_INTEREST"),
        /**
        * 
        */
        KCS_DEDUCTION_FEES("KCS_DEDUCTION_FEES"),
        /**
        * 
        */
        KCS_RETURNED_FEES("KCS_RETURNED_FEES"),
        /**
        * 
        */
        AUTO_EXCHANGE_USER("AUTO_EXCHANGE_USER");

        private final String value;

        BusinessTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static BusinessTypeEnum fromValue(String value) {
          for (BusinessTypeEnum b :  BusinessTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum DirectionEnum {
        /**
        * 
        */
        IN("IN"),
        /**
        * 
        */
        OUT("OUT");

        private final String value;

        DirectionEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static DirectionEnum fromValue(String value) {
          for (DirectionEnum b :  DirectionEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
