// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAccountOverviewResp implements Response<GetAccountOverviewResp, RestResponse<GetAccountOverviewResp>> {
    /**
    * Account type
    */
    @JsonProperty("accountType")
    private String accountType;

    /**
    * **Account Risk Ratio** = (Cross Margin Account Maintenance Margin + Estimated Liquidation Fees) / Cross Margin Account Effective Margin(adjustedEquity)
    */
    @JsonProperty("riskRatio")
    private String riskRatio;

    /**
    * **Account Equity (Undiscounted)** = ∑(Currency Equity * Index Price)
    */
    @JsonProperty("equity")
    private String equity;

    /**
    * **Account Equity after CDR Discount** (Effective Margin) = ∑(Positive Balance of Collateral Currencies × USD Index Price × Haircut Rate) + ∑(Negative Balance of Collateral Currencies × USD Index Price) - Spot (and Margin) Open Order Loss  Notes: CDR stands for Collateral Discount Rate.
    */
    @JsonProperty("adjustedEquity")
    private String adjustedEquity;

    /**
    * **Liability** = ∑(Currency Liability * Index Price)
    */
    @JsonProperty("liability")
    private String liability;

    /**
    * **Available Margin** = adjustedEquity - im
    */
    @JsonProperty("availableMargin")
    private String availableMargin;

    /**
    * **Initial Margin (IM)** = ∑(Margin Reserved per Currency × USD Index Price)
    */
    @JsonProperty("im")
    private String im;

    /**
    * **Maintenance Margin (MM)** = ∑(Maintenance Margin per Currency × USD Index Price)
    */
    @JsonProperty("mm")
    private String mm;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetAccountOverviewResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetAccountOverviewResp> response) {
        this.commonResponse = response;
    }



}
