// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAccountAccountsCurrencies {
    /**
    * **Currency**
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * - Real-time net equity of the UTA account. - Includes unrealized PnL `unPnL` in real time, including `unPnL` from futures positions. - Formula: `equity = balance + unPnL`
    */
    @JsonProperty("equity")
    private String equity;

    /**
    * **Frozen amount** (unavailable) = Spot Orders + Estimated Fees & Taxes Reserved for All Orders
    */
    @JsonProperty("hold")
    private String hold;

    /**
    * - Actual spot balance in the UTA account. - Any balance-changing ledger activity (deposit, withdrawal, transfer, trade settlement, etc.) is applied directly to `balance`.
    */
    @JsonProperty("balance")
    private String balance;

    /**
    * - Available equity of the currency. - Formula: `available = equity - hold`
    */
    @JsonProperty("available")
    private String available;

    /**
    * - Margin-level liability (not separated by trade type). - Liabilities may be generated by Spot Margin, Futures, and other product lines. - Formula: **liability = abs(min(cross-margin currency equity, 0))**
    */
    @JsonProperty("liability")
    private String liability;

    /**
    * - Potential borrowing reserved by open orders, which will turn into liabilities upon execution.
    */
    @JsonProperty("potentialBorrow")
    private String potentialBorrow;

    /**
    * - Platform-level margin collateral status, refer to https://www.kucoin.com/support/48142946141936
    */
    @JsonProperty("collateralStatus")
    private CollateralStatusEnum collateralStatus;



    public enum CollateralStatusEnum {
        /**
        * 
        */
        _1("1"),
        /**
        * 
        */
        _2("2"),
        /**
        * 
        */
        _3("3");

        private final String value;

        CollateralStatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static CollateralStatusEnum fromValue(String value) {
          for (CollateralStatusEnum b :  CollateralStatusEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
