// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetBorrowingRatesAndLimitsResp implements Response<GetBorrowingRatesAndLimitsResp, RestResponse<GetBorrowingRatesAndLimitsResp>> {
    /**
    * Current hourly interest rate
    */
    @JsonProperty("currentRateHourly")
    private String currentRateHourly;

    /**
    * Current daily interest rate
    */
    @JsonProperty("currentRateDaily")
    private String currentRateDaily;

    /**
    * Total borrowing limit for master and sub-accounts
    */
    @JsonProperty("borrowLimitTotal")
    private String borrowLimitTotal;

    /**
    * Total reserved borrowing amount across all master and sub-accounts
    */
    @JsonProperty("borrowLimitTotalHold")
    private String borrowLimitTotalHold;

    /**
    * Current reserved borrowing amount at the user UID level
    */
    @JsonProperty("borrowLimitHold")
    private String borrowLimitHold;

    /**
    * Total interest-free borrowing limit at the user UID level. Note: Only unrealized PnL generated from futures positions is eligible for an interest-free quota. Liabilities arising from unrealized PnL within the quota will not accrue interest.
    */
    @JsonProperty("interestFreeBorrowLimit")
    private String interestFreeBorrowLimit;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetBorrowingRatesAndLimitsResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetBorrowingRatesAndLimitsResp> response) {
        this.commonResponse = response;
    }



}
