// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetClassicAccountBalanceAccounts {
    /**
    * Account subtype. Only available for ISOLATED classic accounts or account types that return a subtype.
    */
    @JsonProperty("accountSubtype")
    private String accountSubtype;

    /**
    * Account subtype returned by some account types, such as FUTURES classic accounts. Field name follows the actual response.
    */
    @JsonProperty("accountSubType")
    private String accountSubType;

    /**
    * Risk ratio. Only available for ISOLATED classic accounts when returned.
    */
    @JsonProperty("riskRatio")
    private String riskRatio;

    /**
    * Currency balance list.
    */
    @JsonProperty("currencies")
    private List<GetClassicAccountBalanceAccountsCurrencies> currencies = new ArrayList<>();



}
