// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetClassicAccountBalanceAccountsCurrencies {
    /**
    * Currency code, such as `USDT` or `BTC`.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Amount currently locked.
    */
    @JsonProperty("locked")
    private String locked;

    /**
    * Amount available for use.
    */
    @JsonProperty("available")
    private String available;

    /**
    * Total balance.
    */
    @JsonProperty("balance")
    private String balance;

    /**
    * Account equity.
    */
    @JsonProperty("equity")
    private String equity;

    /**
    * Margin occupied by open orders in cross-margin futures mode.
    */
    @JsonProperty("crossOrderMargin")
    private String crossOrderMargin;

    /**
    * Margin occupied by positions in cross-margin futures mode.
    */
    @JsonProperty("crossPosMargin")
    private String crossPosMargin;

    /**
    * Unrealised profit and loss of positions in cross-margin futures mode.
    */
    @JsonProperty("crossUnPnl")
    private String crossUnPnl;

    /**
    * Margin reserved for funding fees in isolated-margin futures mode.
    */
    @JsonProperty("isolatedFundingFeeMargin")
    private String isolatedFundingFeeMargin;

    /**
    * Margin occupied by open orders in isolated-margin futures mode.
    */
    @JsonProperty("isolatedOrderMargin")
    private String isolatedOrderMargin;

    /**
    * Margin occupied by positions in isolated-margin futures mode.
    */
    @JsonProperty("isolatedPosMargin")
    private String isolatedPosMargin;

    /**
    * Unrealised profit and loss of positions in isolated-margin futures mode.
    */
    @JsonProperty("isolatedUnPnl")
    private String isolatedUnPnl;

    /**
    * Total margin in cross-margin futures mode.
    */
    @JsonProperty("totalCrossMargin")
    private String totalCrossMargin;

    /**
    * Liability amount.
    */
    @JsonProperty("liability")
    private String liability;



}
