// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetDepositAddressData {
    /**
    * Currency code, such as `USDT` or `BTC`.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Blockchain network identifier used in requests, such as `trx`. It is different from `chainName`, which is the display name such as `TRC20`. Use [Get Currencies](apidog://link/endpoint/3478404) or [Get Currency](apidog://link/endpoint/3478403) to discover supported chain values for each currency.
    */
    @JsonProperty("chain")
    private String chain;

    /**
    * Display name of the blockchain network, such as `TRC20` for `chain=trx`. This value is for display; use `chain` as the API request value.
    */
    @JsonProperty("chainName")
    private String chainName;

    /**
    * Deposit address.
    */
    @JsonProperty("address")
    private String address;

    /**
    * Deposit memo or tag.
    */
    @JsonProperty("memo")
    private String memo;

    /**
    * Remark.
    */
    @JsonProperty("remark")
    private String remark;

    /**
    * Account type credited after deposit.
    */
    @JsonProperty("toAccountType")
    private ToAccountTypeEnum toAccountType;

    /**
    * Token contract address.
    */
    @JsonProperty("contractAddress")
    private String contractAddress;

    /**
    * Address expiration time in milliseconds.
    */
    @JsonProperty("expirationDate")
    private Long expirationDate;



    public enum ToAccountTypeEnum {
        /**
        * 
        */
        FUNDING("FUNDING"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        SPOT("SPOT");

        private final String value;

        ToAccountTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static ToAccountTypeEnum fromValue(String value) {
          for (ToAccountTypeEnum b :  ToAccountTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
