// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetDepositHistoryReq implements Request {
    /**
    * Currency of the deposit records to query. Use an uppercase currency code.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Deposit record ID.
    */
    @JsonProperty("id")
    private String id;

    /**
    * Deposit status.
    */
    @JsonProperty("status")
    private StatusEnum status;

    /**
    * Start time of the query time range, in milliseconds.
    */
    @JsonProperty("startAt")
    private Long startAt;

    /**
    * End time of the query time range, in milliseconds.
    */
    @JsonProperty("endAt")
    private Long endAt;

    /**
    * Page number to query.
    */
    @JsonProperty("currentPage")
    @Builder.Default
    private Long currentPage = 1L;

    /**
    * Number of records to return per page.
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 10L;



    public enum StatusEnum {
        /**
        * 
        */
        FAILURE("FAILURE"),
        /**
        * 
        */
        PRE_SUCCESS("PRE_SUCCESS"),
        /**
        * 
        */
        PROCESSING("PROCESSING"),
        /**
        * 
        */
        RISK_MGT_REJECTED("RISK_MGT_REJECTED"),
        /**
        * 
        */
        ROLLBACK("ROLLBACK"),
        /**
        * 
        */
        ROLLBACKING("ROLLBACKING"),
        /**
        * 
        */
        SUCCESS("SUCCESS"),
        /**
        * 
        */
        TRM_MGT_REJECTED("TRM_MGT_REJECTED"),
        /**
        * 
        */
        WAIT_RISK_MGT("WAIT_RISK_MGT"),
        /**
        * 
        */
        WAIT_TRM_MGT("WAIT_TRM_MGT");

        private final String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(String value) {
          for (StatusEnum b :  StatusEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
