// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetDepositHistoryItems {
    /**
    * Deposit record ID.
    */
    @JsonProperty("id")
    private String id;

    /**
    * Deposit currency.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Blockchain network identifier used in requests, such as `trx`. It is different from `chainName`, which is the display name such as `TRC20`. Use [Get Currencies](apidog://link/endpoint/3478404) or [Get Currency](apidog://link/endpoint/3478403) to discover supported chain values for each currency.
    */
    @JsonProperty("chain")
    private String chain;

    /**
    * Deposit status.
    */
    @JsonProperty("status")
    private StatusEnum status;

    /**
    * Deposit address.
    */
    @JsonProperty("address")
    private String address;

    /**
    * Address memo or tag.
    */
    @JsonProperty("memo")
    private String memo;

    /**
    * Whether the deposit is an internal transfer.
    */
    @JsonProperty("isInner")
    private Boolean isInner;

    /**
    * Deposit amount.
    */
    @JsonProperty("amount")
    private String amount;

    /**
    * Deposit fee.
    */
    @JsonProperty("fee")
    private String fee;

    /**
    * On-chain transaction ID.
    */
    @JsonProperty("walletTxId")
    private String walletTxId;

    /**
    * Time when the deposit record was created, in milliseconds.
    */
    @JsonProperty("createdAt")
    private Long createdAt;

    /**
    * Time when the deposit record was last updated, in milliseconds.
    */
    @JsonProperty("updatedAt")
    private Long updatedAt;

    /**
    * Deposit remark.
    */
    @JsonProperty("remark")
    private String remark;

    /**
    * Whether an on-chain rollback may cause account debt.
    */
    @JsonProperty("arrears")
    private Boolean arrears;

    /**
    * Blockchain explorer URL for the deposit transaction.
    */
    @JsonProperty("url")
    private String url;

    /**
    * Additional deposit status description.
    */
    @JsonProperty("statusRemark")
    private String statusRemark;

    /**
    * Number of pre-confirmations required for early crediting.
    */
    @JsonProperty("preConfirms")
    private Long preConfirms;

    /**
    * Number of confirmations required for final crediting.
    */
    @JsonProperty("confirms")
    private Long confirms;

    /**
    * Current number of confirmations.
    */
    @JsonProperty("currentConfirms")
    private Long currentConfirms;



    public enum StatusEnum {
        /**
        * 
        */
        FAILURE("FAILURE"),
        /**
        * 
        */
        PRE_SUCCESS("PRE_SUCCESS"),
        /**
        * 
        */
        PROCESSING("PROCESSING"),
        /**
        * 
        */
        RISK_MGT_REJECTED("RISK_MGT_REJECTED"),
        /**
        * 
        */
        ROLLBACK("ROLLBACK"),
        /**
        * 
        */
        ROLLBACKING("ROLLBACKING"),
        /**
        * 
        */
        SUCCESS("SUCCESS"),
        /**
        * 
        */
        TRM_MGT_REJECTED("TRM_MGT_REJECTED"),
        /**
        * 
        */
        WAIT_RISK_MGT("WAIT_RISK_MGT"),
        /**
        * 
        */
        WAIT_TRM_MGT("WAIT_TRM_MGT");

        private final String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(String value) {
          for (StatusEnum b :  StatusEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
