// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetDepositAddressReq implements Request {
    /**
    * Blockchain network identifier. Use lowercase chain values. Supported values depend on the currency; common examples include `trx`, `eth`, `btc`, `kcc`, and `bsc`. To discover the available chains for a currency, use [Get Currencies](apidog://link/endpoint/3478404) or [Get Currency](apidog://link/endpoint/3478403).
    */
    @JsonProperty("chain")
    private String chain;

    /**
    * Currency code, such as `USDT` or `BTC`. Currency values use uppercase codes.
    */
    @JsonProperty("currency")
    private String currency;



}
