// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetInterestHistoryReq implements Request {
    /**
    * Account Type
    */
    @JsonProperty("accountType")
    private AccountTypeEnum accountType;

    /**
    * Currency
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * The start time. If no time range is specified, the default is to return all interest accrual records for the past 7 days.
    */
    @JsonProperty("startTime")
    private Long startTime;

    /**
    * The end time. If no time range is specified, the default is to return all interest accrual records for the past 7 days.
    */
    @JsonProperty("endTime")
    private Long endTime;

    /**
    * Current query page
    */
    @JsonProperty("page")
    private Long page;

    /**
    * Number of results per page.
    */
    @JsonProperty("size")
    @Builder.Default
    private Long size = 50L;



    public enum AccountTypeEnum {
        /**
        * 
        */
        UNIFIED("UNIFIED");

        private final String value;

        AccountTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static AccountTypeEnum fromValue(String value) {
          for (AccountTypeEnum b :  AccountTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
