// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetInterestHistoryItems {
    /**
    * Liability Size at Interest Accrual Time
    */
    @JsonProperty("liability")
    private String liability;

    /**
    * Interest Size
    */
    @JsonProperty("interest")
    private String interest;

    /**
    * Interest-Bearing Currency
    */
    @JsonProperty("hourlyInterestRate")
    private String hourlyInterestRate;

    /**
    * Interest-Bearing Currency
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Interest Accrual Timestamp
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * Interest-Exempt Liability Size at the Accrual Time
    */
    @JsonProperty("interestFreeLiability")
    private String interestFreeLiability;



}
