// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetLeverageReq implements Request {
    /**
    * Currency (Cross margin). Required when tradeType is MARGIN, If not filled in, return all
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Symbol (Cross Futures). Required when tradeType is FUTURES, If not filled in, return all
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Trade type. Legal value: MARGIN FUTURES
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Cross or Isolated Margin/Futures
    */
    @JsonProperty("marginMode")
    private MarginModeEnum marginMode;



    public enum TradeTypeEnum {
        /**
        * 
        */
        MARGIN("MARGIN"),
        /**
        * 
        */
        FUTURES("FUTURES");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum MarginModeEnum {
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        ISOLATED("ISOLATED");

        private final String value;

        MarginModeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static MarginModeEnum fromValue(String value) {
          for (MarginModeEnum b :  MarginModeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
