// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOESCustodyQuotaData {
    /**
    * custodian
    */
    @JsonProperty("custodian")
    private String custodian;

    /**
    * settlement currency
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * The user's remaining custodial quota for this token is shared across all custodian sub-accounts under the master account.
    */
    @JsonProperty("custodyQuota")
    private String custodyQuota;



}
