// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOESCustodyQuotaReq implements Request {
    /**
    * Note that if the sub-account API key is used when querying, the interface will ignore the custodian imported parameter and only return the custodian and settlement currency information bound to the sub-account
    */
    @JsonProperty("custodian")
    private CustodianEnum custodian;

    /**
    * Settlement currency code, if not filled in, return the user's remaining limit for all currencies in the designated custodian institution
    */
    @JsonProperty("currency")
    private String currency;



    public enum CustodianEnum {
        /**
        * 
        */
        BITGO_SG("BITGO_SG"),
        /**
        * 
        */
        BITGO_SD("BITGO_SD"),
        /**
        * 
        */
        CACTUS("CACTUS"),
        /**
        * 
        */
        CEFFU("CEFFU");

        private final String value;

        CustodianEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static CustodianEnum fromValue(String value) {
          for (CustodianEnum b :  CustodianEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
