// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetRateLimitCapResp implements Response<GetRateLimitCapResp, RestResponse<GetRateLimitCapResp>> {
    /**
    * 
    */
    @JsonProperty("vipLevel")
    private Long vipLevel;

    /**
    * Main account total rate limit = allocatedQuota + remainingQuota
    */
    @JsonProperty("mainRateLimit")
    private Long mainRateLimit;

    /**
    * Maximum rate limit for sub-accounts
    */
    @JsonProperty("subRateLimit")
    private Long subRateLimit;

    /**
    * Limit quota has been allocated to sub-accounts
    */
    @JsonProperty("allocatedQuota")
    private Long allocatedQuota;

    /**
    * Remaining quota can be allocated to sub-accounts, This is also the rate limit for master account
    */
    @JsonProperty("remainingQuota")
    private Long remainingQuota;

    /**
    * Default quota for new sub-accounts
    */
    @JsonProperty("defaultQuota")
    private Long defaultQuota;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetRateLimitCapResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetRateLimitCapResp> response) {
        this.commonResponse = response;
    }



}
