// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetRateLimitResp implements Response<GetRateLimitResp, RestResponse<GetRateLimitResp>> {
    /**
    * 
    */
    @JsonProperty("list")
    private List<GetRateLimitList> _list = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetRateLimitResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetRateLimitResp> response) {
        this.commonResponse = response;
    }



}
