// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSubAccountListResp implements Response<GetSubAccountListResp, RestResponse<GetSubAccountListResp>> {
    /**
    * Current request page, The default currentPage is 1
    */
    @JsonProperty("currentPage")
    private Long currentPage;

    /**
    * The default pageSize is 10, The maximum cannot exceed 1000
    */
    @JsonProperty("pageSize")
    private Long pageSize;

    /**
    * Total number of sub-accounts matching the query.
    */
    @JsonProperty("totalNum")
    private Long totalNum;

    /**
    * Total number of pages.
    */
    @JsonProperty("totalPage")
    private Long totalPage;

    /**
    * Sub-account list.
    */
    @JsonProperty("items")
    private List<GetSubAccountListItems> items = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetSubAccountListResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetSubAccountListResp> response) {
        this.commonResponse = response;
    }



}
