// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSubAccountListReq implements Request {
    /**
    * Page number to query. The default value is 1.
    */
    @JsonProperty("currentPage")
    @Builder.Default
    private Long currentPage = 1L;

    /**
    * Number of results per request. 
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 10L;



}
