// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSubAccountApiListData {
    /**
    * Sub Name
    */
    @JsonProperty("subName")
    private String subName;

    /**
    * Remarks
    */
    @JsonProperty("remark")
    private String remark;

    /**
    * API Key
    */
    @JsonProperty("apiKey")
    private String apiKey;

    /**
    * API Version
    */
    @JsonProperty("apiVersion")
    private Long apiVersion;

    /**
    * [Permissions](apidog://link/pages/338144) General, Spot, Futures, Margin, Unified, InnerTransfer (Flex Transfer) 
    */
    @JsonProperty("permission")
    private String permission;

    /**
    * IP whitelist
    */
    @JsonProperty("ipWhitelist")
    private String ipWhitelist;

    /**
    * Apikey create time
    */
    @JsonProperty("createdAt")
    private Long createdAt;

    /**
    * Sub-account UID
    */
    @JsonProperty("uid")
    private Long uid;

    /**
    * Whether it is the master account.
    */
    @JsonProperty("isMaster")
    private Boolean isMaster;



}
