// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSubAccountBalanceUserListAccountsCurrencies {
    /**
    * Currency code, such as `USDT` or `BTC`.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Amount currently locked.
    */
    @JsonProperty("locked")
    private String locked;

    /**
    * Amount available for use.
    */
    @JsonProperty("available")
    private String available;

    /**
    * Total balance.
    */
    @JsonProperty("balance")
    private String balance;

    /**
    * Account equity.
    */
    @JsonProperty("equity")
    private String equity;

    /**
    * Liability amount.
    */
    @JsonProperty("liability")
    private String liability;

    /**
    * Liability interest.
    */
    @JsonProperty("liabilityInterest")
    private String liabilityInterest;

    /**
    * Liability principal.
    */
    @JsonProperty("liabilityPrincipal")
    private String liabilityPrincipal;

    /**
    * Unrealised profit and loss.
    */
    @JsonProperty("unrealisedPnl")
    private String unrealisedPnl;



}
