// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSubAccountBalanceResp implements Response<GetSubAccountBalanceResp, RestResponse<GetSubAccountBalanceResp>> {
    /**
    * Timestamp in milliseconds.
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * Sub-account balance list.
    */
    @JsonProperty("userList")
    private List<GetSubAccountBalanceUserList> userList = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetSubAccountBalanceResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetSubAccountBalanceResp> response) {
        this.commonResponse = response;
    }



}
