// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSubAccountBalanceUserList {
    /**
    * Sub-account user ID.
    */
    @JsonProperty("uid")
    private Long uid;

    /**
    * Account groups.
    */
    @JsonProperty("accounts")
    private List<GetSubAccountBalanceUserListAccounts> accounts = new ArrayList<>();



}
