// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSubAccountBalanceReq implements Request {
    /**
    * Sub-account user ID. If omitted, balances for all sub-accounts are returned.
    */
    @JsonProperty("uid")
    private String uid;

    /**
    * Number of records to return per page.
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 10L;

    /**
    * ID of the last record from the previous page. If omitted, the latest records are returned.
    */
    @JsonProperty("lastId")
    private Long lastId;



}
