// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSubAccountListItems {
    /**
    * Sub-account user ID.
    */
    @JsonProperty("userId")
    private String userId;

    /**
    * Sub-account UID
    */
    @JsonProperty("uid")
    private Long uid;

    /**
    * Sub-account name
    */
    @JsonProperty("subName")
    private String subName;

    /**
    * Sub-account status.
    */
    @JsonProperty("status")
    private StatusEnum status;

    /**
    * Sub-account type.
    */
    @JsonProperty("type")
    private TypeEnum type;

    /**
    * Sub-account access permission. In UTA mode, only `ALL` is returned, meaning all trading types are supported. In Classic mode, possible values are `ALL`, `FUTURES`, and `MARGIN`.
    */
    @JsonProperty("access")
    private AccessEnum access;

    /**
    * Time when the sub-account was created.
    */
    @JsonProperty("createdAt")
    private Long createdAt;

    /**
    * Sub-account remarks.
    */
    @JsonProperty("remarks")
    private String remarks;

    /**
    * Trading permissions assigned to the sub-account.
    */
    @JsonProperty("tradeTypes")
    private List<TradeTypesEnum> tradeTypes = new ArrayList<>();

    /**
    * Trading permissions that have been activated for the sub-account.
    */
    @JsonProperty("openedTradeTypes")
    private List<OpenedTradeTypesEnum> openedTradeTypes = new ArrayList<>();

    /**
    * Hosted status of the sub-account.
    */
    @JsonProperty("hostedStatus")
    private HostedStatusEnum hostedStatus;



    public enum StatusEnum {
        /**
        * 
        */
        _2(2),
        /**
        * 
        */
        _3(3);

        private final Integer value;

        StatusEnum(Integer value) {
            this.value = value;
        }

        @JsonValue
        public Integer getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(Integer value) {
          for (StatusEnum b :  StatusEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TypeEnum {
        /**
        * 
        */
        _0(0),
        /**
        * 
        */
        _1(1),
        /**
        * 
        */
        _2(2),
        /**
        * 
        */
        _5(5);

        private final Integer value;

        TypeEnum(Integer value) {
            this.value = value;
        }

        @JsonValue
        public Integer getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TypeEnum fromValue(Integer value) {
          for (TypeEnum b :  TypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum AccessEnum {
        /**
        * 
        */
        ALL("All"),
        /**
        * 
        */
        FUTURES("Futures"),
        /**
        * 
        */
        MARGIN("Margin");

        private final String value;

        AccessEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static AccessEnum fromValue(String value) {
          for (AccessEnum b :  AccessEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TradeTypesEnum {
        /**
        * 
        */
        SPOT("Spot"),
        /**
        * 
        */
        FUTURES("Futures"),
        /**
        * 
        */
        MARGIN("Margin");

        private final String value;

        TradeTypesEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypesEnum fromValue(String value) {
          for (TradeTypesEnum b :  TradeTypesEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum OpenedTradeTypesEnum {
        /**
        * 
        */
        SPOT("Spot"),
        /**
        * 
        */
        FUTURES("Futures"),
        /**
        * 
        */
        MARGIN("Margin"),

        OPTION("Option");

        private final String value;

        OpenedTradeTypesEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static OpenedTradeTypesEnum fromValue(String value) {
          for (OpenedTradeTypesEnum b :  OpenedTradeTypesEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum HostedStatusEnum {
        /**
        * 
        */
        _0(0),
        /**
        * 
        */
        _1(1),
        /**
        * 
        */
        _2(2),
        /**
        * 
        */
        _3(3),
        /**
        * 
        */
        _4(4),
        /**
        * 
        */
        _5(5);

        private final Integer value;

        HostedStatusEnum(Integer value) {
            this.value = value;
        }

        @JsonValue
        public Integer getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static HostedStatusEnum fromValue(Integer value) {
          for (HostedStatusEnum b :  HostedStatusEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
