// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTransferQuotaResp implements Response<GetTransferQuotaResp, RestResponse<GetTransferQuotaResp>> {
    /**
    * Account type.
    */
    @JsonProperty("accountType")
    private AccountTypeEnum accountType;

    /**
    * Currency code, such as `USDT` or `BTC`.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Amount currently transferable out of the specified account type for this currency.
    */
    @JsonProperty("transferable")
    private String transferable;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetTransferQuotaResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetTransferQuotaResp> response) {
        this.commonResponse = response;
    }



    public enum AccountTypeEnum {
        /**
        * 
        */
        FUNDING("FUNDING"),
        /**
        * 
        */
        UNIFIED("UNIFIED"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        SPOT("SPOT");

        private final String value;

        AccountTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static AccountTypeEnum fromValue(String value) {
          for (AccountTypeEnum b :  AccountTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
