// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTransferQuotaReq implements Request {
    /**
    * Account type used to calculate the transferable amount. Supported values include `FUNDING`, `SPOT`, `FUTURES`, `CROSS`, `ISOLATED`, and `UNIFIED`.
    */
    @JsonProperty("accountType")
    private AccountTypeEnum accountType;

    /**
    * Currency code, such as `USDT` or `BTC`. Currency values use uppercase codes in API examples.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Trading pair symbol required for isolated margin account queries, such as `BTC-USDT`. Omit this field for account types that do not use a symbol.
    */
    @JsonProperty("symbol")
    private String symbol;



    public enum AccountTypeEnum {
        /**
        * 
        */
        FUNDING("FUNDING"),
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES"),
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        ISOLATED("ISOLATED"),
        /**
        * 
        */
        UNIFIED("UNIFIED");

        private final String value;

        AccountTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static AccountTypeEnum fromValue(String value) {
          for (AccountTypeEnum b :  AccountTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
