// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetWithdrawalQuotasResp implements Response<GetWithdrawalQuotasResp, RestResponse<GetWithdrawalQuotasResp>> {
    /**
    * Currency code, such as `USDT` or `BTC`.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Blockchain network identifier used in requests, such as `trx`. It is different from `chainName`, which is the display name such as `TRC20`. Use [Get Currencies](apidog://link/endpoint/3478404) or [Get Currency](apidog://link/endpoint/3478403) to discover supported chain values for each currency.
    */
    @JsonProperty("chain")
    private String chain;

    /**
    * Display name of the blockchain network, such as `TRC20` for `chain=trx`. This value is for display; use `chain` as the API request value.
    */
    @JsonProperty("chainName")
    private String chainName;

    /**
    * Whether withdrawals are enabled.
    */
    @JsonProperty("isWithdrawEnabled")
    private Boolean isWithdrawEnabled;

    /**
    * Reason withdrawals are unavailable.
    */
    @JsonProperty("reason")
    private String reason;

    /**
    * Amount available to withdraw.
    */
    @JsonProperty("availableWithdrawAmount")
    private String availableWithdrawAmount;

    /**
    * Remaining withdrawal quota.
    */
    @JsonProperty("remainingQuotaAmount")
    private String remainingQuotaAmount;

    /**
    * Locked amount.
    */
    @JsonProperty("lockedAmount")
    private String lockedAmount;

    /**
    * Minimum withdrawal amount. This value depends on the requested `withdrawType`; the minimum for `ADDRESS` on-chain withdrawals can differ from `MAIL`, `PHONE`, and `UID` internal withdrawals.
    */
    @JsonProperty("withdrawMinSize")
    private String withdrawMinSize;

    /**
    * Minimum withdrawal fee.
    */
    @JsonProperty("minWithdrawFee")
    private String minWithdrawFee;

    /**
    * Minimum internal withdrawal fee.
    */
    @JsonProperty("minInnerWithdrawFee")
    private String minInnerWithdrawFee;

    /**
    * Currency precision.
    */
    @JsonProperty("precision")
    private Long precision;

    /**
    * Currency used to calculate withdrawal quota.
    */
    @JsonProperty("quotaCurrency")
    private String quotaCurrency;

    /**
    * Withdrawal quota limit in quota currency.
    */
    @JsonProperty("limitQuotaCurrencyAmount")
    private String limitQuotaCurrencyAmount;

    /**
    * Used withdrawal quota in quota currency.
    */
    @JsonProperty("usedQuotaCurrencyAmount")
    private String usedQuotaCurrencyAmount;

    /**
    * Withdrawal quota limit converted to BTC.
    */
    @JsonProperty("limitBTCAmount")
    private String limitBTCAmount;

    /**
    * Used withdrawal quota converted to BTC.
    */
    @JsonProperty("usedBTCAmount")
    private String usedBTCAmount;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetWithdrawalQuotasResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetWithdrawalQuotasResp> response) {
        this.commonResponse = response;
    }



}
