// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetWithdrawalHistoryResp implements Response<GetWithdrawalHistoryResp, RestResponse<GetWithdrawalHistoryResp>> {
    /**
    * Current page number.
    */
    @JsonProperty("currentPage")
    private Long currentPage;

    /**
    * Number of records returned per page.
    */
    @JsonProperty("pageSize")
    private Long pageSize;

    /**
    * Total number of withdrawal records matching the query.
    */
    @JsonProperty("totalNum")
    private Long totalNum;

    /**
    * Total number of pages.
    */
    @JsonProperty("totalPage")
    private Long totalPage;

    /**
    * Withdrawal record list.
    */
    @JsonProperty("items")
    private List<GetWithdrawalHistoryItems> items = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetWithdrawalHistoryResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetWithdrawalHistoryResp> response) {
        this.commonResponse = response;
    }



}
