// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetWithdrawalQuotasReq implements Request {
    /**
    * Blockchain network identifier. Use lowercase chain values. Supported values depend on the currency; common examples include `trx`, `eth`, `btc`, `kcc`, and `bsc`. To discover the available chains for a currency, use [Get Currencies](apidog://link/endpoint/3478404) or [Get Currency](apidog://link/endpoint/3478403).
    */
    @JsonProperty("chain")
    private String chain;

    /**
    * Currency code, such as `USDT` or `BTC`. Currency values use uppercase codes in API examples.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Whether to query quota information for an internal withdrawal. Set to `true` for internal transfers within the platform; set to `false` for withdrawals to an external address.
    */
    @JsonProperty("isInner")
    private Boolean isInner;

    /**
    * Withdrawal destination type. `ADDRESS` means an on-chain address withdrawal; `MAIL`, `PHONE`, and `UID` mean internal withdrawals. The minimum withdrawal amount can differ by withdrawal type; use the returned `withdrawMinSize` for the selected type.
    */
    @JsonProperty("withdrawType")
    private WithdrawTypeEnum withdrawType;



    public enum WithdrawTypeEnum {
        /**
        * 
        */
        ADDRESS("ADDRESS"),
        /**
        * 
        */
        MAIL("MAIL"),
        /**
        * 
        */
        PHONE("PHONE"),
        /**
        * 
        */
        UID("UID");

        private final String value;

        WithdrawTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static WithdrawTypeEnum fromValue(String value) {
          for (WithdrawTypeEnum b :  WithdrawTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
