// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ModifyMarginCrossLeverageResp implements Response<ModifyMarginCrossLeverageResp, RestResponse<ModifyMarginCrossLeverageResp>> {
    /**
    * 
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * 
    */
    @JsonProperty("leverage")
    private String leverage;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<ModifyMarginCrossLeverageResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<ModifyMarginCrossLeverageResp> response) {
        this.commonResponse = response;
    }



}
