// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ModifySubAccountApiResp implements Response<ModifySubAccountApiResp, RestResponse<ModifySubAccountApiResp>> {
    /**
    * Sub-account name
    */
    @JsonProperty("subName")
    private String subName;

    /**
    * API Key
    */
    @JsonProperty("apiKey")
    private String apiKey;

    /**
    * [Permissions](apidog://link/pages/338144) General, Spot, Futures, Margin, Unified, InnerTransfer (Flex Transfer)
    */
    @JsonProperty("permission")
    private String permission;

    /**
    * IP whitelist
    */
    @JsonProperty("ipWhitelist")
    private String ipWhitelist;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<ModifySubAccountApiResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<ModifySubAccountApiResp> response) {
        this.commonResponse = response;
    }



}
