// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class SetAccountModeResp implements Response<SetAccountModeResp, RestResponse<SetAccountModeResp>> {
    /**
    * 
    */
    @JsonProperty("data")
    private String data;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<SetAccountModeResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<SetAccountModeResp> response) {
        this.commonResponse = response;
    }

    @JsonCreator
    public static SetAccountModeResp fromJson(String data) {
        // original response
        SetAccountModeResp obj = new SetAccountModeResp();
        obj.data = data;
        return obj;
    }

    @JsonValue
    public Object toJson() {
        return this.data;
    }



}
