// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class SetKcsFeeDeductionResp implements Response<SetKcsFeeDeductionResp, RestResponse<SetKcsFeeDeductionResp>> {
    /**
    * Whether KCS fee deduction is enabled.
    */
    @JsonProperty("enabled")
    private Boolean enabled;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<SetKcsFeeDeductionResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<SetKcsFeeDeductionResp> response) {
        this.commonResponse = response;
    }



}
