// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class SetSubAccountTransferPermissionResp implements Response<SetSubAccountTransferPermissionResp, RestResponse<SetSubAccountTransferPermissionResp>> {
    /**
    * 
    */
    @JsonProperty("data")
    private List<SetSubAccountTransferPermissionData> data = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<SetSubAccountTransferPermissionResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<SetSubAccountTransferPermissionResp> response) {
        this.commonResponse = response;
    }

    @JsonCreator
    public static SetSubAccountTransferPermissionResp fromJson(List<SetSubAccountTransferPermissionData> data) {
        // original response
        SetSubAccountTransferPermissionResp obj = new SetSubAccountTransferPermissionResp();
        obj.data = data;
        return obj;
    }

    @JsonValue
    public Object toJson() {
        return this.data;
    }



}
