// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class SetSubAccountTransferPermissionReq implements Request {
    /**
    * Sub account UID
    */
    @JsonProperty("subUids")
    private String subUids;

    /**
    * true: Supports SUB_TO_SUB transfers initiated by the sub-account API key false: Not supported
    */
    @JsonProperty("subToSub")
    private Boolean subToSub;



}
