// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class SetSubAccountTransferPermissionData {
    /**
    * Sub-account UID
    */
    @JsonProperty("subUid")
    private String subUid;

    /**
    * true: Supports initiating SUB_TO_SUB transfers using this sub-account API key. false: Not supported.
    */
    @JsonProperty("subToSub")
    private Boolean subToSub;



}
