// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class WithdrawalV3Req implements Request {
    /**
    * Withdrawal currency, such as `BTC`, `ETH`, or `USDT`. Use uppercase currency codes.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Blockchain network identifier of the currency. For a currency with multiple chains, specify `chain` instead of using the default chain; query available `chain` values from [Get Currencies](apidog://link/endpoint/3478404).
    */
    @JsonProperty("chain")
    private String chain;

    /**
    * Withdrawal amount, a positive number that must match the amount precision of the currency.
    */
    @JsonProperty("amount")
    private String amount;

    /**
    * Withdrawal address
    */
    @JsonProperty("toAddress")
    private String toAddress;

    /**
    * Memo, tag, payment ID, or similar destination identifier used by some currencies and chains to credit the withdrawal to the correct recipient account. This field is optional at the API schema level, but required when the selected chain or receiving platform requires it. Check `data[].list[].isMemoRequired` and `data[].list[].memoRegex` from [Get Currencies](apidog://link/endpoint/3478404), and enter the exact value provided by the recipient. Do not enter a random value or provide one for a chain that does not support it. A missing or incorrect value may cause the withdrawal not to be credited and may result in loss of funds.
    */
    @JsonProperty("memo")
    private String memo;

    /**
    * Withdrawal remark.
    */
    @JsonProperty("remark")
    private String remark;

    /**
    * Whether this is an internal withdrawal. Default: `false`.
    */
    @JsonProperty("isInner")
    private Boolean isInner;

    /**
    * Withdrawal type: `ADDRESS` for an on-chain withdrawal address, `UID`, `MAIL`, and `PHONE` for internal withdrawals. Withdrawals by UID, email, or phone are rate-limited to 3 requests per 10 seconds and 50 requests per 24 hours, calculated on a rolling basis from the first request time.
    */
    @JsonProperty("withdrawType")
    private WithdrawTypeEnum withdrawType;

    /**
    * Withdrawal fee deduction type. If this parameter is omitted, the system first deducts the fee from the main account when the main account balance is sufficient. If the main account balance is insufficient, the fee is deducted from the withdrawal amount. For example, when withdrawing 1 BTC with a 0.0001 BTC fee, the received amount is 0.9999 BTC if the fee is deducted from the withdrawal amount.
    */
    @JsonProperty("feeDeductType")
    private FeeDeductTypeEnum feeDeductType;



    public enum WithdrawTypeEnum {
        /**
        * 
        */
        ADDRESS("ADDRESS"),
        /**
        * 
        */
        MAIL("MAIL"),
        /**
        * 
        */
        PHONE("PHONE"),
        /**
        * 
        */
        UID("UID");

        private final String value;

        WithdrawTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static WithdrawTypeEnum fromValue(String value) {
          for (WithdrawTypeEnum b :  WithdrawTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum FeeDeductTypeEnum {
        /**
        * 
        */
        INTERNAL("INTERNAL"),
        /**
        * 
        */
        EXTERNAL("EXTERNAL");

        private final String value;

        FeeDeductTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static FeeDeductTypeEnum fromValue(String value) {
          for (FeeDeductTypeEnum b :  FeeDeductTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
