// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class WithdrawalV3Resp implements Response<WithdrawalV3Resp, RestResponse<WithdrawalV3Resp>> {
    /**
    * Unique withdrawal request ID.
    */
    @JsonProperty("withdrawalId")
    private String withdrawalId;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<WithdrawalV3Resp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<WithdrawalV3Resp> response) {
        this.commonResponse = response;
    }



}
