// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;
import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class AffiliateApiImpl implements AffiliateApi {
    private final Transport transport;

    public AffiliateApiImpl(Transport transport)
    {
        this.transport = transport;
    }

    public  GetInvitedResp getInvited(GetInvitedReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/affiliate/queryInvitees", req, GetInvitedResp.class, false);
    }

    public  GetKuminingResp getKumining(GetKuminingReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/affiliate/queryKumining", req, GetKuminingResp.class, false);
    }

    public  GetCommissionResp getCommission(GetCommissionReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/affiliate/queryMyCommission", req, GetCommissionResp.class, false);
    }

    public  GetTransactionResp getTransaction(GetTransactionReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/affiliate/queryTransactionByTime", req, GetTransactionResp.class, false);
    }

    public  GetTradeHistoryResp getTradeHistory(GetTradeHistoryReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/affiliate/queryTransactionByUid", req, GetTradeHistoryResp.class, false);
    }

}