// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

public interface AffiliateApi {
    /**
    * Get Invited
    *
    * <p>:::info[Description] Affiliate user invited information can be obtained at this endpoint. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    GetInvitedResp getInvited(GetInvitedReq req);

    /**
    * Get Kumining
    *
    * <p>:::info[Description] The kumining information can be obtained at this endpoint. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    GetKuminingResp getKumining(GetKuminingReq req);

    /**
    * Get Commission
    *
    * <p>:::info[Description] My commission information can be obtained at this endpoint. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    GetCommissionResp getCommission(GetCommissionReq req);

    /**
    * Get Transaction
    *
    * <p>:::info[Description] Transaction information can be obtained at this endpoint. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    GetTransactionResp getTransaction(GetTransactionReq req);

    /**
    * Get Trade History
    *
    * <p>:::info[Description] Trade history information can be obtained at this endpoint. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 30
    * </ul>
    *
    */

    GetTradeHistoryResp getTradeHistory(GetTradeHistoryReq req);

}