// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCommissionData {
    /**
    * Source site of the commission
    */
    @JsonProperty("siteType")
    private String siteType;

    /**
    * Rebate type
    */
    @JsonProperty("rebateType")
    private RebateTypeEnum rebateType;

    /**
    * Commission payout time (T+1 settlement), 13-digit timestamp (UTC+8)
    */
    @JsonProperty("payoutTime")
    private Long payoutTime;

    /**
    * Start time of commission calculation period, 13-digit timestamp
    */
    @JsonProperty("periodStartTime")
    private Long periodStartTime;

    /**
    * End time of commission calculation period, 13-digit timestamp
    */
    @JsonProperty("periodEndTime")
    private Long periodEndTime;

    /**
    * Payout status
    */
    @JsonProperty("status")
    private StatusEnum status;

    /**
    * Invitee's taker trading volume
    */
    @JsonProperty("takerVolume")
    private String takerVolume;

    /**
    * Invitee's maker trading volume
    */
    @JsonProperty("makerVolume")
    private String makerVolume;

    /**
    * Total rebate contributed by the invitee
    */
    @JsonProperty("commission")
    private String commission;

    /**
    * Denomination unit for trading volume/amount (USDT or USDC)
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * The volume of kumining
    */
    @JsonProperty("kuminingVolume")
    private String kuminingVolume;

    /**
    * Data type
    */
    @JsonProperty("dataType")
    private DataTypeEnum dataType;



    public enum RebateTypeEnum {
        /**
        * 
        */
        _1(1),
        /**
        * 
        */
        _2(2);

        private final Integer value;

        RebateTypeEnum(Integer value) {
            this.value = value;
        }

        @JsonValue
        public Integer getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static RebateTypeEnum fromValue(Integer value) {
          for (RebateTypeEnum b :  RebateTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum StatusEnum {
        /**
        * 
        */
        _1(1),
        /**
        * 
        */
        _2(2),
        /**
        * 
        */
        _3(3),
        /**
        * 
        */
        _4(4);

        private final Integer value;

        StatusEnum(Integer value) {
            this.value = value;
        }

        @JsonValue
        public Integer getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(Integer value) {
          for (StatusEnum b :  StatusEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum DataTypeEnum {
        /**
        * 
        */
        TRADE("trade"),
        /**
        * 
        */
        KUMINING("kumining");

        private final String value;

        DataTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static DataTypeEnum fromValue(String value) {
          for (DataTypeEnum b :  DataTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
