// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCommissionResp implements Response<GetCommissionResp, RestResponse<GetCommissionResp>> {
    /**
    * Current page number
    */
    @JsonProperty("currentPage")
    private Long currentPage;

    /**
    * Number of records per page
    */
    @JsonProperty("pageSize")
    private Long pageSize;

    /**
    * Total number of records
    */
    @JsonProperty("totalNum")
    private Long totalNum;

    /**
    * Total number of pages
    */
    @JsonProperty("totalPage")
    private Long totalPage;

    /**
    * Commission records
    */
    @JsonProperty("items")
    private List<GetCommissionData> items = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetCommissionResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetCommissionResp> response) {
        this.commonResponse = response;
    }

}
