// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetInvitedResp implements Response<GetInvitedResp, RestResponse<GetInvitedResp>> {
    /**
    * 
    */
    @JsonProperty("items")
    private List<GetInvitedItems> items = new ArrayList<>();

    /**
    * 
    */
    @JsonProperty("pageSize")
    private Long pageSize;

    /**
    * 
    */
    @JsonProperty("totalNum")
    private Long totalNum;

    /**
    * 
    */
    @JsonProperty("totalPage")
    private Long totalPage;

    /**
    * 
    */
    @JsonProperty("currentPage")
    private Long currentPage;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetInvitedResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetInvitedResp> response) {
        this.commonResponse = response;
    }



}
