// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetInvitedReq implements Request {
    /**
    * Invited user type
    */
    @JsonProperty("userType")
    private UserTypeEnum userType;

    /**
    * Which referral code the user registered with
    */
    @JsonProperty("referralCode")
    private String referralCode;

    /**
    * User UID(s): when passing multiple UIDs, separate them with commas ,
    */
    @JsonProperty("uid")
    private String uid;

    /**
    * Registration start timestamp
    */
    @JsonProperty("registrationEndAt")
    private Long registrationEndAt;

    /**
    * Registration end timestamp
    */
    @JsonProperty("registrationStartAt")
    private Long registrationStartAt;

    /**
    * Page number
    */
    @JsonProperty("page")
    @Builder.Default
    private Long page = 1L;

    /**
    * Max number of records per page
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 10L;



    public enum UserTypeEnum {
        /**
        * 
        */
        _1("1"),
        /**
        * 
        */
        _2("2"),
        /**
        * 
        */
        _3("3");

        private final String value;

        UserTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static UserTypeEnum fromValue(String value) {
          for (UserTypeEnum b :  UserTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
