// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetInvitedItems {
    /**
    * Invitee's UID
    */
    @JsonProperty("uid")
    private String uid;

    /**
    * Invitee's country.
    */
    @JsonProperty("country")
    private String country;

    /**
    * Unit for trading volume or amount, either USDT or USDC.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Invitee's nickname. If no nickname exists, it will be a desensitized phone number or email.
    */
    @JsonProperty("nickName")
    private String nickName;

    /**
    * Fees generated in the past 7 days.
    */
    @JsonProperty("past7dFees")
    private String past7dFees;

    /**
    * Total commission contributed by the invitee.
    */
    @JsonProperty("cashbackRate")
    private String cashbackRate;

    /**
    * Whether KYC has been completed.
    */
    @JsonProperty("completedKyc")
    private Boolean completedKyc;

    /**
    * The referral code (rcode) through which the user registered.
    */
    @JsonProperty("referralCode")
    private String referralCode;

    /**
    * My commission rate (percentage-based, e.g., 70 means 70%).
    */
    @JsonProperty("totalCommission")
    private String totalCommission;

    /**
    * Invitee's cashback rate (percentage-based, e.g., 10 means 10%).
    */
    @JsonProperty("myCommissionRate")
    private String myCommissionRate;

    /**
    * Commission contributed in the past 7 days.
    */
    @JsonProperty("past7dCommission")
    private String past7dCommission;

    /**
    * Invitee's registration time, as a 13-digit timestamp.
    */
    @JsonProperty("registrationTime")
    private Long registrationTime;

    /**
    * Whether the first trade has been completed.
    */
    @JsonProperty("completedFirstTrade")
    private Boolean completedFirstTrade;

    /**
    * Whether the first deposit has been completed.
    */
    @JsonProperty("completedFirstDeposit")
    private Boolean completedFirstDeposit;



}
