// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetKuminingReq implements Request {
    /**
    * User UID, please separate multiple UIDs with commas.
    */
    @JsonProperty("uid")
    private String uid;

    /**
    * Start time
    */
    @JsonProperty("startAt")
    private Long startAt;

    /**
    * End time
    */
    @JsonProperty("endAt")
    private Long endAt;

    /**
    * The offset ID of the query is an empty string for the first query, and the lastId field of the last data in the response is used for subsequent queries.
    */
    @JsonProperty("lastId")
    private String lastId;

    /**
    * Page direction
    */
    @JsonProperty("direction")
    private DirectionEnum direction;

    /**
    * Number of items per page
    */
    @JsonProperty("pageSize")
    private Long pageSize;



    public enum DirectionEnum {
        /**
        * 
        */
        PRE("PRE"),
        /**
        * 
        */
        NEXT("NEXT");

        private final String value;

        DirectionEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static DirectionEnum fromValue(String value) {
          for (DirectionEnum b :  DirectionEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
