// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetKuminingResp implements Response<GetKuminingResp, RestResponse<GetKuminingResp>> {
    /**
    * 
    */
    @JsonProperty("data")
    private List<GetKuminingData> data = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetKuminingResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetKuminingResp> response) {
        this.commonResponse = response;
    }

    @JsonCreator
    public static GetKuminingResp fromJson(List<GetKuminingData> data) {
        // original response
        GetKuminingResp obj = new GetKuminingResp();
        obj.data = data;
        return obj;
    }

    @JsonValue
    public Object toJson() {
        return this.data;
    }



}
