// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetKuminingData {
    /**
    * User Id
    */
    @JsonProperty("uid")
    private String uid;

    /**
    * Trade time
    */
    @JsonProperty("payTime")
    private Long payTime;

    /**
    * Product Name
    */
    @JsonProperty("goodsName")
    private String goodsName;

    /**
    * Product amount
    */
    @JsonProperty("amount")
    private String amount;

    /**
    * The currency
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Last Id
    */
    @JsonProperty("lastId")
    private String lastId;



}
