// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTradeHistoryItems {
    /**
    * User's trade timestamp
    */
    @JsonProperty("tradeTime")
    private Long tradeTime;

    /**
    * Trade type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Trading pair symbol
    */
    @JsonProperty("tradeCurrency")
    private String tradeCurrency;

    /**
    * Trade amount (denominated in trading pair currency)
    */
    @JsonProperty("tradeAmount")
    private String tradeAmount;

    /**
    * Trade amount converted to USD equivalent (USDT or USDC)
    */
    @JsonProperty("tradeAmountU")
    private String tradeAmountU;

    /**
    * Trading fee converted to USD equivalent (USDT or USDC)
    */
    @JsonProperty("feeU")
    private String feeU;

    /**
    * Commission generated from this trade
    */
    @JsonProperty("commission")
    private String commission;

    /**
    * Denomination unit for trading volume/amount (USDT or USDC)
    */
    @JsonProperty("currency")
    private String currency;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FEATURE("FEATURE");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
