// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTransactionData {
    /**
    * The uid of the invitee
    */
    @JsonProperty("uid")
    private String uid;

    /**
    * Trade time
    */
    @JsonProperty("tradeTime")
    private Long tradeTime;

    /**
    * Trade type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Trade currency
    */
    @JsonProperty("tradeCurrency")
    private String tradeCurrency;

    /**
    * Trade amount
    */
    @JsonProperty("tradeAmount")
    private String tradeAmount;

    /**
    * Trade amount transfer to U(USDT or usdt)
    */
    @JsonProperty("tradeAmountU")
    private String tradeAmountU;

    /**
    * Fee transfer to U(USDT or usdt)
    */
    @JsonProperty("feeU")
    private String feeU;

    /**
    * Trade commission
    */
    @JsonProperty("commission")
    private String commission;

    /**
    * Transaction volume or amount converted to U
    */
    @JsonProperty("currency")
    private CurrencyEnum currency;

    /**
    * The offset ID
    */
    @JsonProperty("lastId")
    private String lastId;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum CurrencyEnum {
        /**
        * 
        */
        USDT("USDT"),
        /**
        * 
        */
        USDC("USDC");

        private final String value;

        CurrencyEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static CurrencyEnum fromValue(String value) {
          for (CurrencyEnum b :  CurrencyEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
