// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTradeHistoryReq implements Request {
    /**
    * Invitee's UID
    */
    @JsonProperty("uid")
    private String uid;

    /**
    * Trading type, SPOT- spot trading, FUTURES- futures trading
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Trade start time (13-digit timestamp). If end time is provided, must be earlier than end time.
    */
    @JsonProperty("tradeStartAt")
    private Long tradeStartAt;

    /**
    * Trade end time (13-digit timestamp). If start time is provided, must be later than start time.
    */
    @JsonProperty("tradeEndAt")
    private Long tradeEndAt;

    /**
    * Page number
    */
    @JsonProperty("page")
    @Builder.Default
    private Long page = 1L;

    /**
    * Page size
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 10L;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FEATURE("FEATURE");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
