// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.affiliate;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTransactionReq implements Request {
    /**
    * The uid of the invitee
    */
    @JsonProperty("uid")
    private String uid;

    /**
    * Trade type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Transaction start time. If an end time is specified, it must be earlier than the end time. 13-digit timestamp
    */
    @JsonProperty("tradeStartAt")
    private Long tradeStartAt;

    /**
    * Transaction end time. If a start time is entered, it must be earlier than the start time. 13-digit timestamp
    */
    @JsonProperty("tradeEndAt")
    private Long tradeEndAt;

    /**
    * The offset ID of the query is an empty string for the first query, and the lastId field of the last data in the response is used for subsequent queries.
    */
    @JsonProperty("lastId")
    private Long lastId;

    /**
    * Page direction: PRE - Previous Page, NEXT - Next Page
    */
    @JsonProperty("direction")
    @Builder.Default
    private DirectionEnum direction = DirectionEnum.NEXT;

    /**
    * Page size
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 10L;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FEATURE("FEATURE");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum DirectionEnum {
        /**
        * 
        */
        PRE("PRE"),
        /**
        * 
        */
        NEXT("NEXT");

        private final String value;

        DirectionEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static DirectionEnum fromValue(String value) {
          for (DirectionEnum b :  DirectionEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
