// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAnnouncementsResp implements Response<GetAnnouncementsResp, RestResponse<GetAnnouncementsResp>> {
    /**
    * Total Number
    */
    @JsonProperty("totalNumber")
    private Long totalNumber;

    /**
    * Total Page
    */
    @JsonProperty("totalPage")
    private Long totalPage;

    /**
    * pageNumber
    */
    @JsonProperty("pageNumber")
    private Long pageNumber;

    /**
    * Page size
    */
    @JsonProperty("pageSize")
    private Long pageSize;

    /**
    * 
    */
    @JsonProperty("list")
    private List<GetAnnouncementsList> _list = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetAnnouncementsResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetAnnouncementsResp> response) {
        this.commonResponse = response;
    }



}
