// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAnnouncementsReq implements Request {
    /**
    * Language type
    */
    @JsonProperty("language")
    @Builder.Default
    private LanguageEnum language = LanguageEnum.ENUS;

    /**
    * Announcement types
    */
    @JsonProperty("type")
    @Builder.Default
    private TypeEnum type = TypeEnum.LATESTANNOUNCEMENTS;

    /**
    * Page number
    */
    @JsonProperty("pageNumber")
    private Long pageNumber;

    /**
    * Page size
    */
    @JsonProperty("pageSize")
    private Long pageSize;

    /**
    * Announcement online start time (milliseconds)
    */
    @JsonProperty("startTime")
    private Long startTime;

    /**
    * Announcement online end time (milliseconds)
    */
    @JsonProperty("endTime")
    private Long endTime;



    public enum LanguageEnum {
        /**
        * 
        */
        ZHHK("zh_HK"),
        /**
        * 
        */
        JAJP("ja_JP"),
        /**
        * 
        */
        KOKR("ko_KR"),
        /**
        * 
        */
        ENUS("en_US"),
        /**
        * 
        */
        PLPL("pl_PL"),
        /**
        * 
        */
        ESES("es_ES"),
        /**
        * 
        */
        FRFR("fr_FR"),
        /**
        * 
        */
        ARAE("ar_AE"),
        /**
        * 
        */
        ITIT("it_IT"),
        /**
        * 
        */
        IDID("id_ID"),
        /**
        * 
        */
        NLNL("nl_NL"),
        /**
        * 
        */
        PTPT("pt_PT"),
        /**
        * 
        */
        VIVN("vi_VN"),
        /**
        * 
        */
        DEDE("de_DE"),
        /**
        * 
        */
        TRTR("tr_TR"),
        /**
        * 
        */
        MSMY("ms_MY"),
        /**
        * 
        */
        RURU("ru_RU"),
        /**
        * 
        */
        THTH("th_TH"),
        /**
        * 
        */
        HIIN("hi_IN"),
        /**
        * 
        */
        BNBD("bn_BD"),
        /**
        * 
        */
        FILPH("fil_PH"),
        /**
        * 
        */
        URPK("ur_PK");

        private final String value;

        LanguageEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static LanguageEnum fromValue(String value) {
          for (LanguageEnum b :  LanguageEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TypeEnum {
        /**
        * 
        */
        LATESTANNOUNCEMENTS("latest-announcements"),
        /**
        * 
        */
        ACTIVITIES("activities"),
        /**
        * 
        */
        PRODUCTUPDATES("product-updates"),
        /**
        * 
        */
        VIP("vip"),
        /**
        * 
        */
        MAINTENANCEUPDATES("maintenance-updates"),
        /**
        * 
        */
        DELISTINGS("delistings"),
        /**
        * 
        */
        OTHERS("others"),
        /**
        * 
        */
        APICAMPAIGNS("api-campaigns"),
        /**
        * 
        */
        NEWLISTINGS("new-listings"),
        /**
        * 
        */
        FUTURESANNOUNCEMENTS("futures-announcements");

        private final String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
          for (TypeEnum b :  TypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
