// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAnnouncementsList {
    /**
    * Announcement ID
    */
    @JsonProperty("id")
    private Long id;

    /**
    * Announcement title
    */
    @JsonProperty("title")
    private String title;

    /**
    * Announcement type
    */
    @JsonProperty("type")
    private List<String> type = new ArrayList<>();

    /**
    * Announcement description
    */
    @JsonProperty("description")
    private String description;

    /**
    * Announcement release time, Unix millisecond timestamp format
    */
    @JsonProperty("releaseTime")
    private Long releaseTime;

    /**
    * language type
    */
    @JsonProperty("language")
    private String language;

    /**
    * Announcement link
    */
    @JsonProperty("url")
    private String url;



}
