// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCollateralRatioData {
    /**
    * Currency
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * 
    */
    @JsonProperty("cdrConfigs")
    private List<GetCollateralRatioDataCdrConfigs> cdrConfigs = new ArrayList<>();



}
