// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCollateralRatioDataCdrConfigs {
    /**
    * Risk tier number, smaller number = higher priority/tier
    */
    @JsonProperty("tier")
    private Long tier;

    /**
    * Minimum equity threshold for this tier (in target currency)
    */
    @JsonProperty("min")
    private String min;

    /**
    * Maximum equity threshold for this tier (in target currency)
    */
    @JsonProperty("max")
    private String max;

    /**
    * Cross‑asset discount rate
    */
    @JsonProperty("cdr")
    private String cdr;

    /**
    * Max equity eligible for cross‑asset conversion under this tier
    */
    @JsonProperty("cdrEquity")
    private String cdrEquity;



}
