// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCallAuctionInfoResp implements Response<GetCallAuctionInfoResp, RestResponse<GetCallAuctionInfoResp>> {
    /**
    * Symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Estimated trading size
    */
    @JsonProperty("estimatedSize")
    private String estimatedSize;

    /**
    * Estimated trading price
    */
    @JsonProperty("estimatedPrice")
    private String estimatedPrice;

    /**
    * Minimum declared buy price
    */
    @JsonProperty("buyOrderRangeLowPrice")
    private String buyOrderRangeLowPrice;

    /**
    * Maximum declared buy price
    */
    @JsonProperty("buyOrderRangeHighPrice")
    private String buyOrderRangeHighPrice;

    /**
    * Minimum declared selling price
    */
    @JsonProperty("sellOrderRangeLowPrice")
    private String sellOrderRangeLowPrice;

    /**
    * Maximum declared selling price
    */
    @JsonProperty("sellOrderRangeHighPrice")
    private String sellOrderRangeHighPrice;

    /**
    * Estimated price time
    */
    @JsonProperty("time")
    private Long time;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetCallAuctionInfoResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetCallAuctionInfoResp> response) {
        this.commonResponse = response;
    }



}
