// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCurrenciesData {
    /**
    * Currency code, such as `USDT`, `BTC`, or `ETH`.
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Short display name of the currency.
    */
    @JsonProperty("name")
    private String name;

    /**
    * Full display name of the currency.
    */
    @JsonProperty("fullName")
    private String fullName;

    /**
    * Currency precision.
    */
    @JsonProperty("precision")
    private Long precision;

    /**
    * List of items.
    */
    @JsonProperty("list")
    private List<GetCurrenciesDataList> _list = new ArrayList<>();



}
