// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCurrentFundingRatesReq implements Request {
    /**
    * Symbol of the contract. When symbol is set, productType will be ignored. 
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Futures product type. If symbol and productType are not passed or set empty, all funding fee rates for all trading symbols are returned.
    */
    @JsonProperty("productType")
    private ProductTypeEnum productType;



    public enum ProductTypeEnum {
        /**
        * 
        */
        COIN_FUTURES("COIN-FUTURES"),
        /**
        * 
        */
        USDC_FUTURES("USDC-FUTURES"),
        /**
        * 
        */
        USDT_FUTURES("USDT-FUTURES");

        private final String value;

        ProductTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static ProductTypeEnum fromValue(String value) {
          for (ProductTypeEnum b :  ProductTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
