// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCurrenciesReq implements Request {
    /**
    * Blockchain network identifier. Use lowercase chain values. Supported values depend on the currency; common examples include `trx`, `eth`, `btc`, `kcc`, and `bsc`. To discover the available chains for a currency, use `GET /api/ua/v2/asset/currencies` or `GET /api/ua/v2/market/currency`.
    */
    @JsonProperty("chain")
    private String chain;

    /**
    * Currency code list used to filter the result. Use uppercase currency codes. If omitted, all currencies are returned.
    */
    @JsonProperty("currencyList")
    @Builder.Default
    private List<String> currencyList = new ArrayList<>();



}
