// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCurrencyList {
    /**
    * Blockchain network identifier used in requests, such as `trx`. It is different from `chainName`, which is the display name such as `TRC20`. Use [Get Currencies](apidog://link/endpoint/3478404) to discover supported chain values for each currency.
    */
    @JsonProperty("chain")
    private String chain;

    /**
    * Display name of the blockchain network, such as `TRC20` for `chain=trx`. This value is for display; use `chain` as the API request value.
    */
    @JsonProperty("chainName")
    private String chainName;

    /**
    * Whether deposits are enabled.
    */
    @JsonProperty("isDepositEnabled")
    private Boolean isDepositEnabled;

    /**
    * Whether withdrawals are enabled.
    */
    @JsonProperty("isWithdrawEnabled")
    private Boolean isWithdrawEnabled;

    /**
    * Whether a memo or tag is required for deposits or withdrawals on this chain. If `true`, users must provide the required memo/tag together with the address.
    */
    @JsonProperty("isMemoRequired")
    private Boolean isMemoRequired;

    /**
    * Number of blockchain confirmations required before a deposit is considered confirmed for this currency on this chain.
    */
    @JsonProperty("confirms")
    private Long confirms;

    /**
    * Number of confirmations used for preliminary deposit recognition on this chain, when supported.
    */
    @JsonProperty("preConfirms")
    private Long preConfirms;

    /**
    * Regular expression used to validate withdrawal addresses on this chain. Empty means no regex is provided.
    */
    @JsonProperty("addressRegex")
    private String addressRegex;

    /**
    * Regular expression used to validate the memo or tag on this chain. Empty means no regex is provided.
    */
    @JsonProperty("memoRegex")
    private String memoRegex;

    /**
    * Token contract address for this currency on this chain. For example, USDT on TRC20 uses a TRON contract address; native assets may return an empty value.
    */
    @JsonProperty("contractAddress")
    private String contractAddress;

    /**
    * Deposit fee rate.
    */
    @JsonProperty("depositFeeRate")
    private String depositFeeRate;

    /**
    * Tiered deposit fee.
    */
    @JsonProperty("depositTierFee")
    private String depositTierFee;

    /**
    * Fixed deposit fee.
    */
    @JsonProperty("fixedDepositFee")
    private String fixedDepositFee;

    /**
    * Maximum deposit fee.
    */
    @JsonProperty("maxDepositFee")
    private String maxDepositFee;

    /**
    * Minimum deposit amount.
    */
    @JsonProperty("minDepositSize")
    private String minDepositSize;

    /**
    * Maximum deposit amount.
    */
    @JsonProperty("maxDepositSize")
    private String maxDepositSize;

    /**
    * Withdrawal fee rate.
    */
    @JsonProperty("withdrawFeeRate")
    private String withdrawFeeRate;

    /**
    * Withdrawal precision.
    */
    @JsonProperty("withdrawPrecision")
    private Long withdrawPrecision;

    /**
    * Minimum withdrawal amount.
    */
    @JsonProperty("minWithdrawSize")
    private String minWithdrawSize;

    /**
    * Maximum withdrawal amount.
    */
    @JsonProperty("maxWithdrawSize")
    private String maxWithdrawSize;

    /**
    * Minimum withdrawal fee.
    */
    @JsonProperty("minWithdrawFee")
    private String minWithdrawFee;

    /**
    * Maximum withdrawal fee.
    */
    @JsonProperty("maxWithdrawFee")
    private String maxWithdrawFee;



}
