// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCurrentFundingRatesData {
    /**
    * Funding rate symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Next funding fee settlement time point (milliseconds)
    */
    @JsonProperty("fundingTime")
    private Long fundingTime;

    /**
    * Maximum funding rate
    */
    @JsonProperty("fundingRateCap")
    private String fundingRateCap;

    /**
    * New funding fee settlement interval
    */
    @JsonProperty("newGranularity")
    private Long newGranularity;

    /**
    * Next cycle funding rate
    */
    @JsonProperty("nextFundingRate")
    private String nextFundingRate;

    /**
    * Minimum funding rate
    */
    @JsonProperty("fundingRateFloor")
    private String fundingRateFloor;

    /**
    * Current funding fee settlement interval
    */
    @JsonProperty("currentGranularity")
    private Long currentGranularity;

    /**
    * New funding fee settlement interval effective time
    */
    @JsonProperty("newGranularityStartTime")
    private Long newGranularityStartTime;



}
