// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetFiatPriceReq implements Request {
    /**
    * Fiat currency used as the pricing base, such as `USD`, `EUR`, or `CNY`.
    */
    @JsonProperty("base")
    private String base;

    /**
    * Currency code list to query, such as `BTC`, `ETH`, and `USDT`. Currency values use uppercase codes in API examples. If omitted, prices for all supported currencies are returned.
    */
    @JsonProperty("currencies")
    @Builder.Default
    private List<String> currencies = new ArrayList<>();



}
