// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetHistoryFundingRateResp implements Response<GetHistoryFundingRateResp, RestResponse<GetHistoryFundingRateResp>> {
    /**
    * Symbol of the contract
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * List of funding rate history records
    */
    @JsonProperty("list")
    private List<GetHistoryFundingRateList> _list = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetHistoryFundingRateResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetHistoryFundingRateResp> response) {
        this.commonResponse = response;
    }



}
