// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetIndexPriceItemsDecompositionList {
    /**
    * Name of the exchange
    */
    @JsonProperty("exchange")
    private String exchange;

    /**
    * Spot price reported by this exchange at the timestamp.
    */
    @JsonProperty("price")
    private Double price;

    /**
    * Weight assigned to this exchange in the index calculation (values sum to approximately 1 across all exchanges).
    */
    @JsonProperty("weight")
    private Double weight;



}
