// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetIndexPriceItems {
    /**
    * The symbol 
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * The time interval between data points in milliseconds (e.g., 1000 = 1 second).
    */
    @JsonProperty("granularity")
    private Long granularity;

    /**
    * Unix timestamp of the data point in milliseconds (epoch time × 1000).
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * The calculated weighted index price for the symbol at this timestamp.
    */
    @JsonProperty("indexPrice")
    private Double indexPrice;

    /**
    * List of individual exchange prices and their weights used to compute the weighted index price.
    */
    @JsonProperty("decompositionList")
    private List<GetIndexPriceItemsDecompositionList> decompositionList = new ArrayList<>();



}
