// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetInterestRateIndexItems {
    /**
    * Timestamp in milliseconds
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * Contract symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Interest rate value
    */
    @JsonProperty("interestRate")
    private String interestRate;



}
