// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetIndexPriceReq implements Request {
    /**
    * Symbol of the contract. 
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Start time (milliseconds)
    */
    @JsonProperty("startAt")
    private Long startAt;

    /**
    * End time (milliseconds)
    */
    @JsonProperty("endAt")
    private Long endAt;

    /**
    * Max. record count.
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 50L;

    /**
    * Pass the lastId from the previous response to fetch the next batch of older historical records.
    */
    @JsonProperty("lastId")
    private Long lastId;



}
