// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetKlinesReq implements Request {
    /**
    * Symbol, Support query symbol corresponding index price, mark price, premium index
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Product type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Specify the K-line data type. tradeType = SPOT only supports TRADE (or not, using default values); tradeType = FUTURES supports all four types TRADE,MARK_PRICE,INDEX_PRICE,PREMIUM_INDEX
    */
    @JsonProperty("klineType")
    @Builder.Default
    private KlineTypeEnum klineType = KlineTypeEnum.TRADE;

    /**
    * Type of candlestick patterns: 1min, 3min, 5min, 15min, 30min, 1hour, 2hour, 4hour, 6hour, 8hour, 12hour, 1day, 3day, 1week, 1month Currently Futures does not support 6hour and 3day.
    */
    @JsonProperty("interval")
    private IntervalEnum interval;

    /**
    * Start time (second), default is 0
    */
    @JsonProperty("startAt")
    @Builder.Default
    private Long startAt = 0l;

    /**
    * End time (second), default is 0
    */
    @JsonProperty("endAt")
    @Builder.Default
    private Long endAt = 0l;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum KlineTypeEnum {
        /**
        * 
        */
        TRADE("TRADE"),
        /**
        * 
        */
        MARK_PRICE("MARK_PRICE"),
        /**
        * 
        */
        INDEX_PRICE("INDEX_PRICE"),
        /**
        * 
        */
        PREMIUM_INDEX("PREMIUM_INDEX");

        private final String value;

        KlineTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static KlineTypeEnum fromValue(String value) {
          for (KlineTypeEnum b :  KlineTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum IntervalEnum {
        /**
        * 
        */
        _1MIN("1min"),
        /**
        * 
        */
        _3MIN("3min"),
        /**
        * 
        */
        _5MIN("5min"),
        /**
        * 
        */
        _15MIN("15min"),
        /**
        * 
        */
        _30MIN("30min"),
        /**
        * 
        */
        _1HOUR("1hour"),
        /**
        * 
        */
        _2HOUR("2hour"),
        /**
        * 
        */
        _4HOUR("4hour"),
        /**
        * 
        */
        _6HOUR("6hour"),
        /**
        * 
        */
        _8HOUR("8hour"),
        /**
        * 
        */
        _12HOUR("12hour"),
        /**
        * 
        */
        _1DAY("1day"),
        /**
        * 
        */
        _3DAY("3day"),
        /**
        * 
        */
        _1WEEK("1week"),
        /**
        * 
        */
        _1MONTH("1month");

        private final String value;

        IntervalEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static IntervalEnum fromValue(String value) {
          for (IntervalEnum b :  IntervalEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
