// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetMaxOrderQuantityResp implements Response<GetMaxOrderQuantityResp, RestResponse<GetMaxOrderQuantityResp>> {
    /**
    * Trading symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Maximum buy quantity
    */
    @JsonProperty("maxBuySize")
    private String maxBuySize;

    /**
    * Maximum sell quantity
    */
    @JsonProperty("maxSellSize")
    private String maxSellSize;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetMaxOrderQuantityResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetMaxOrderQuantityResp> response) {
        this.commonResponse = response;
    }



}
