// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOpenInterestResp implements Response<GetOpenInterestResp, RestResponse<GetOpenInterestResp>> {
    /**
    * 
    */
    @JsonProperty("data")
    private List<GetOpenInterestData> data = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetOpenInterestResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetOpenInterestResp> response) {
        this.commonResponse = response;
    }

    @JsonCreator
    public static GetOpenInterestResp fromJson(List<GetOpenInterestData> data) {
        // original response
        GetOpenInterestResp obj = new GetOpenInterestResp();
        obj.data = data;
        return obj;
    }

    @JsonValue
    public Object toJson() {
        return this.data;
    }



}
