// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOpenInterestData {
    /**
    * By No. of Contracts For example: 1 contract = 0.001 BTC
    */
    @JsonProperty("openInterest")
    private String openInterest;

    /**
    * 
    */
    @JsonProperty("ts")
    private Long ts;



}
