// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOrderBookReq implements Request {
    /**
    * Product type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * orderbook level - SPOT: 20/100/FULL - Futures: 20/100/FULL
    */
    @JsonProperty("limit")
    private LimitEnum limit;

    /**
    * Whether it is an [RPI Order](apidog://link/pages/338146). Applicable to **FUTURES**
    */
    @JsonProperty("rpiFilter")
    @Builder.Default
    private RpiFilterEnum rpiFilter = RpiFilterEnum._0;



    public enum TradeTypeEnum {
        /**
        * 
        */
        SPOT("SPOT"),
        /**
        * 
        */
        FUTURES("FUTURES");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum LimitEnum {
        /**
        * 
        */
        _20("20"),
        /**
        * 
        */
        _100("100"),
        /**
        * 
        */
        FULL("FULL");

        private final String value;

        LimitEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static LimitEnum fromValue(String value) {
          for (LimitEnum b :  LimitEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum RpiFilterEnum {
        /**
        * 
        */
        _0(0),
        /**
        * 
        */
        _1(1);

        private final Integer value;

        RpiFilterEnum(Integer value) {
            this.value = value;
        }

        @JsonValue
        public Integer getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static RpiFilterEnum fromValue(Integer value) {
          for (RpiFilterEnum b :  RpiFilterEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
