// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOpenInterestReq implements Request {
    /**
    * Specifies the Futures symbols to query. - **Interval Mode:**   - Only **one symbol** is allowed. - **Realtime Mode:**   - Up to **10 symbols** may be specified.     - If not provided, the API returns real-time open interest data for **all symbols**.
    */
    @JsonProperty("symbol")
    @Builder.Default
    private List<String> symbol = new ArrayList<>();

    /**
    * Specifies the time interval for querying **interval-based open interest data**.
    */
    @JsonProperty("interval")
    private IntervalEnum interval;

    /**
    * Start time, in milliseconds.
    */
    @JsonProperty("startAt")
    private Long startAt;

    /**
    * End time, in milliseconds.
    */
    @JsonProperty("endAt")
    private Long endAt;

    /**
    * Specifies the number of records to return per page. - **Only effective in Interval Mode**. - Ignored in Realtime Mode.
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 30L;



    public enum IntervalEnum {
        /**
        * 
        */
        _5MIN("5min"),
        /**
        * 
        */
        _15MIN("15min"),
        /**
        * 
        */
        _30MIN("30min"),
        /**
        * 
        */
        _1HOUR("1hour"),
        /**
        * 
        */
        _4HOUR("4hour"),
        /**
        * 
        */
        _1DAY("1day");

        private final String value;

        IntervalEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static IntervalEnum fromValue(String value) {
          for (IntervalEnum b :  IntervalEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
