// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOEScurrencyData {
    /**
    * custodian
    */
    @JsonProperty("custodian")
    private String custodian;

    /**
    * settlement currency
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * currency precision
    */
    @JsonProperty("precision")
    private Long precision;



}
