// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetPositionTiersData {
    /**
    * Currency
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Trading pair
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * User tier
    */
    @JsonProperty("tier")
    private Long tier;

    /**
    * Lower limit 
    */
    @JsonProperty("minSize")
    private String minSize;

    /**
    * Upper limit
    */
    @JsonProperty("maxSize")
    private String maxSize;

    /**
    * Max leverage
    */
    @JsonProperty("maxLeverage")
    private String maxLeverage;

    /**
    * Maintenance margin rate
    */
    @JsonProperty("maintainMarginRate")
    private String maintainMarginRate;

    /**
    * Maintenance margin deduction for futures. The maintenance margin is calculated as: Notional Value × maintainMarginRate − quickCalOffset.
    */
    @JsonProperty("quickCalOffset")
    private String quickCalOffset;



}
