// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetPositionTiersReq implements Request {
    /**
    * Trade type
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;

    /**
    * Currency  - support multiple entires, separated by commas, up to a maximum of 10. - This field is required when the 'data' parameter is set to 'BORROW'
    */
    @JsonProperty("currency")
    private String currency;

    /**
    * Margin mode
    */
    @JsonProperty("marginMode")
    private MarginModeEnum marginMode;

    /**
    * Data type
    */
    @JsonProperty("data")
    private DataEnum data;

    /**
    * Account type
    */
    @JsonProperty("accountType")
    private String accountType;

    /**
    * Trading pair.  - support multiple entires, separated by commas - This field is required when the 'data' parameter is set to 'RISK_LIMIT'
    */
    @JsonProperty("symbol")
    private String symbol;



    public enum TradeTypeEnum {
        /**
        * 
        */
        MARGIN("MARGIN"),
        /**
        * 
        */
        FUTURES("FUTURES");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum MarginModeEnum {
        /**
        * 
        */
        CROSS("CROSS");

        private final String value;

        MarginModeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static MarginModeEnum fromValue(String value) {
          for (MarginModeEnum b :  MarginModeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum DataEnum {
        /**
        * 
        */
        BORROW("BORROW"),
        /**
        * 
        */
        RISK_LIMIT("RISK_LIMIT");

        private final String value;

        DataEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static DataEnum fromValue(String value) {
          for (DataEnum b :  DataEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
