// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSymbolList {
    /**
    * Instrument symbol. Spot, cross margin, and isolated margin use symbols such as `BTC-USDT`; futures use contract symbols such as `XBTUSDTM`.
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Display name of the symbol or contract.
    */
    @JsonProperty("name")
    private String name;

    /**
    * Base currency of the symbol. For futures this can be the contract base currency, such as `XBT`.
    */
    @JsonProperty("baseCurrency")
    private String baseCurrency;

    /**
    * Quote currency of the symbol or contract.
    */
    @JsonProperty("quoteCurrency")
    private String quoteCurrency;

    /**
    * Market category. (Only applicable to spot and cross margin)
    */
    @JsonProperty("market")
    private String market;

    /**
    * Currency used to charge trading fees. (Only applicable to spot and cross margin)
    */
    @JsonProperty("feeCurrency")
    private String feeCurrency;

    /**
    * Trading status used to determine whether the symbol or contract is currently tradable. For spot symbols, possible values are TradingEnabled and TradingDisabled. For futures contracts, possible values are Init, Open, PrepareSettled, BeingSettled, Settled, Paused, Closed, and CancelOnly.
    */
    @JsonProperty("tradingStatus")
    private TradingStatusEnum tradingStatus;

    /**
    * Price limit ratio for order price validation. Applicable products depend on the returned `tradeType`.
    */
    @JsonProperty("priceLimitRatio")
    private String priceLimitRatio;

    /**
    * Fee category of the symbol, used to determine the fee class that applies to the trading pair. (Only applicable to spot)
    */
    @JsonProperty("feeCategory")
    private FeeCategoryEnum feeCategory;

    /**
    * Maker fee coefficient. (Only applicable to spot)
    */
    @JsonProperty("makerFeeCoefficient")
    private String makerFeeCoefficient;

    /**
    * Taker fee coefficient. (Only applicable to spot)
    */
    @JsonProperty("takerFeeCoefficient")
    private String takerFeeCoefficient;

    /**
    * Whether the instrument is marked as ST. (Only applicable to spot)
    */
    @JsonProperty("st")
    private Boolean st;

    /**
    * Minimum order size in base currency. (Only applicable to spot and cross margin)
    */
    @JsonProperty("minBaseOrderSize")
    private String minBaseOrderSize;

    /**
    * Maximum order size in base currency. For futures, this is the maximum contract order size returned by the futures product.
    */
    @JsonProperty("maxBaseOrderSize")
    private String maxBaseOrderSize;

    /**
    * Base currency order size increment. (Only applicable to spot and cross margin)
    */
    @JsonProperty("baseOrderStep")
    private String baseOrderStep;

    /**
    * Minimum order amount in quote currency. (Only applicable to spot and cross margin)
    */
    @JsonProperty("minQuoteOrderSize")
    private String minQuoteOrderSize;

    /**
    * Maximum order amount in quote currency. (Only applicable to spot and cross margin)
    */
    @JsonProperty("maxQuoteOrderSize")
    private String maxQuoteOrderSize;

    /**
    * Quote currency order amount increment. (Only applicable to spot and cross margin)
    */
    @JsonProperty("quoteOrderStep")
    private String quoteOrderStep;

    /**
    * Minimum price increment. The order price must follow this step.
    */
    @JsonProperty("tickSize")
    private String tickSize;

    /**
    * Minimum order funds requirement. (Only applicable to spot)
    */
    @JsonProperty("minFunds")
    private String minFunds;

    /**
    * Whether call auction is enabled. (Only applicable to spot)
    */
    @JsonProperty("callauctionIsEnabled")
    private Boolean callauctionIsEnabled;

    /**
    * Call auction price floor. (Only applicable to spot)
    */
    @JsonProperty("callauctionPriceFloor")
    private String callauctionPriceFloor;

    /**
    * Call auction price ceiling. (Only applicable to spot)
    */
    @JsonProperty("callauctionPriceCeiling")
    private String callauctionPriceCeiling;

    /**
    * Call auction first stage start time. (Only applicable to spot)
    */
    @JsonProperty("callauctionFirstStageStartTime")
    private String callauctionFirstStageStartTime;

    /**
    * Call auction second stage start time. (Only applicable to spot)
    */
    @JsonProperty("callauctionSecondStageStartTime")
    private String callauctionSecondStageStartTime;

    /**
    * Call auction third stage start time. (Only applicable to spot)
    */
    @JsonProperty("callauctionThirdStageStartTime")
    private String callauctionThirdStageStartTime;

    /**
    * Trading start time. For futures, this can be returned as the contract first trading start time. (Only applicable to spot and futures)
    */
    @JsonProperty("tradingStartTime")
    private Long tradingStartTime;

    /**
    * Maximum leverage. (Only applicable to isolated margin and futures)
    */
    @JsonProperty("maxLeverage")
    private String maxLeverage;

    /**
    * Maximum buy price allowed by the current futures price limit. (Only applicable to futures)
    */
    @JsonProperty("buyLimit")
    private String buyLimit;

    /**
    * Display base currency of the contract. (Only applicable to futures)
    */
    @JsonProperty("displayBaseCurrency")
    private String displayBaseCurrency;

    /**
    * Contract expiry time, when applicable. (Only applicable to futures)
    */
    @JsonProperty("expiryTime")
    private String expiryTime;

    /**
    * Whether the contract is inverse. (Only applicable to futures)
    */
    @JsonProperty("isInverse")
    private Boolean isInverse;

    /**
    * Minimum contract quantity increment. (Only applicable to futures)
    */
    @JsonProperty("lotSize")
    private String lotSize;

    /**
    * Maximum market order size.
    */
    @JsonProperty("maxMarketOrderSize")
    private String maxMarketOrderSize;

    /**
    * Maker fee rate. (Only applicable to futures)
    */
    @JsonProperty("makerFeeRate")
    private String makerFeeRate;

    /**
    * Current futures market stage. (Only applicable to futures)
    */
    @JsonProperty("marketStage")
    private String marketStage;

    /**
    * Futures market type. (Only applicable to futures)
    */
    @JsonProperty("marketType")
    private String marketType;

    /**
    * Maximum order price allowed for the contract. (Only applicable to futures)
    */
    @JsonProperty("maxPrice")
    private String maxPrice;

    /**
    * Time when a pre-market contract converts to a perpetual contract, when applicable.
    */
    @JsonProperty("preMarketToPerpDate")
    private String preMarketToPerpDate;

    /**
    * Contract unit size. (Only applicable to futures)
    */
    @JsonProperty("unitSize")
    private String unitSize;

    /**
    * Exchanges used as index price sources. (Only applicable to futures)
    */
    @JsonProperty("indexSourceExchanges")
    private List<String> indexSourceExchanges = new ArrayList<>();

    /**
    * Taker fee rate. (Only applicable to futures)
    */
    @JsonProperty("takerFeeRate")
    private String takerFeeRate;

    /**
    * Settlement fee rate, when applicable. (Only applicable to futures)
    */
    @JsonProperty("settlementFeeRate")
    private String settlementFeeRate;

    /**
    * Settlement time, when applicable. (Only applicable to futures)
    */
    @JsonProperty("settlementTime")
    private String settlementTime;

    /**
    * Settlement currency of the contract. (Only applicable to futures)
    */
    @JsonProperty("settlementCurrency")
    private String settlementCurrency;

    /**
    * Minimum sell price allowed by the current futures price limit. (Only applicable to futures)
    */
    @JsonProperty("sellLimit")
    private String sellLimit;

    /**
    * Index price tick size. (Only applicable to futures)
    */
    @JsonProperty("indexPriceTickSize")
    private String indexPriceTickSize;

    /**
    * Contract type code: `0` indicates a perpetual contract, and `1` indicates a delivery contract. (Only applicable to futures)
    */
    @JsonProperty("contractType")
    private ContractTypeEnum contractType;



    public enum TradingStatusEnum {
        /**
        * 
        */
        TRADINGENABLED("TradingEnabled"),
        /**
        * 
        */
        TRADINGDISABLED("TradingDisabled"),
        /**
        * 
        */
        INIT("Init"),
        /**
        * 
        */
        OPEN("Open"),
        /**
        * 
        */
        PREPARESETTLED("PrepareSettled"),
        /**
        * 
        */
        BEINGSETTLED("BeingSettled"),
        /**
        * 
        */
        SETTLED("Settled"),
        /**
        * 
        */
        PAUSED("Paused"),
        /**
        * 
        */
        CLOSED("Closed"),
        /**
        * 
        */
        CANCELONLY("CancelOnly");

        private final String value;

        TradingStatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradingStatusEnum fromValue(String value) {
          for (TradingStatusEnum b :  TradingStatusEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum FeeCategoryEnum {
        /**
        * 
        */
        CLASSA("classA"),
        /**
        * 
        */
        CLASSB("classB"),
        /**
        * 
        */
        CLASSC("classC");

        private final String value;

        FeeCategoryEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static FeeCategoryEnum fromValue(String value) {
          for (FeeCategoryEnum b :  FeeCategoryEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum ContractTypeEnum {
        /**
        * 
        */
        _0("0"),
        /**
        * 
        */
        _1("1");

        private final String value;

        ContractTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static ContractTypeEnum fromValue(String value) {
          for (ContractTypeEnum b :  ContractTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
