// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTradeResp implements Response<GetTradeResp, RestResponse<GetTradeResp>> {
    /**
    * Product type
    */
    @JsonProperty("tradeType")
    private String tradeType;

    /**
    * List of trade data
    */
    @JsonProperty("list")
    private List<GetTradeList> _list = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetTradeResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetTradeResp> response) {
        this.commonResponse = response;
    }



}
