// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTradeStatisticsResp implements Response<GetTradeStatisticsResp, RestResponse<GetTradeStatisticsResp>> {
    /**
    * 
    */
    @JsonProperty("spot")
    private GetTradeStatisticsSpot spot;

    /**
    * 
    */
    @JsonProperty("futures")
    private GetTradeStatisticsFutures futures;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetTradeStatisticsResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetTradeStatisticsResp> response) {
        this.commonResponse = response;
    }



}
