// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTradeList {
    /**
    * Sequence number
    */
    @JsonProperty("sequence")
    private Long sequence;

    /**
    * Trade identifier
    */
    @JsonProperty("tradeId")
    private String tradeId;

    /**
    * Filled price
    */
    @JsonProperty("price")
    private String price;

    /**
    * Filled amount
    */
    @JsonProperty("size")
    private String size;

    /**
    * Filled side, indicates the taker order side. A taker order is the order that was matched with orders opened on the order book.
    */
    @JsonProperty("side")
    private SideEnum side;

    /**
    * Filled timestamp (nanoseconds)
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * Whether it is an [RPI Order](apidog://link/pages/338146). Applicable to **FUTURES**
    */
    @JsonProperty("isRpiTrade")
    private Boolean isRpiTrade;



    public enum SideEnum {
        /**
        * 
        */
        BUY("BUY"),
        /**
        * 
        */
        SELL("SELL");

        private final String value;

        SideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SideEnum fromValue(String value) {
          for (SideEnum b :  SideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
