// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTickerResp implements Response<GetTickerResp, RestResponse<GetTickerResp>> {
    /**
    * Product type
    */
    @JsonProperty("tradeType")
    private String tradeType;

    /**
    * Timestamp (nanoseconds)
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * List of trading pair data
    */
    @JsonProperty("list")
    private List<GetTickerList> _list = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetTickerResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetTickerResp> response) {
        this.commonResponse = response;
    }



}
