// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTickerList {
    /**
    * Symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Name of trading pairs
    */
    @JsonProperty("name")
    private String name;

    /**
    * Best bid price
    */
    @JsonProperty("bestBidPrice")
    private String bestBidPrice;

    /**
    * Best bid size
    */
    @JsonProperty("bestBidSize")
    private String bestBidSize;

    /**
    * Best ask price
    */
    @JsonProperty("bestAskPrice")
    private String bestAskPrice;

    /**
    * Best ask size
    */
    @JsonProperty("bestAskSize")
    private String bestAskSize;

    /**
    * Last traded price
    */
    @JsonProperty("lastPrice")
    private String lastPrice;

    /**
    * Last traded size
    */
    @JsonProperty("size")
    private String size;

    /**
    * Opening price in 24h
    */
    @JsonProperty("open")
    private String open;

    /**
    * Highest price in 24h
    */
    @JsonProperty("high")
    private String high;

    /**
    * Lowest price in 24h
    */
    @JsonProperty("low")
    private String low;

    /**
    * the base volume returns an add up of maker and taker volume per transaction. 
    */
    @JsonProperty("baseVolume")
    private String baseVolume;

    /**
    * the quote volume returns an add up of maker and taker volume per transaction. 
    */
    @JsonProperty("quoteVolume")
    private String quoteVolume;

    /**
    * 24h price change
    */
    @JsonProperty("priceChange")
    private String priceChange;

    /**
    * 24h price change rate
    */
    @JsonProperty("priceChangePercent")
    private String priceChangePercent;

    /**
    * Index price
    */
    @JsonProperty("indexPrice")
    private String indexPrice;

    /**
    * Mark price
    */
    @JsonProperty("markPrice")
    private String markPrice;



}
