// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;
import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class MarketApiImpl implements MarketApi {
    private final Transport transport;

    public MarketApiImpl(Transport transport)
    {
        this.transport = transport;
    }

    public  GetAnnouncementsResp getAnnouncements(GetAnnouncementsReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/announcement", req, GetAnnouncementsResp.class, false);
    }

    public  GetBorrowableCurrenciesResp getBorrowableCurrencies(){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/borrowable-currency", null, GetBorrowableCurrenciesResp.class, false);
    }

    public  GetCollateralRatioResp getCollateralRatio(){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/collateral-discount-ratio", null, GetCollateralRatioResp.class, false);
    }

    public  GetHistoryFundingRateResp getHistoryFundingRate(GetHistoryFundingRateReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/funding-rate-history", req, GetHistoryFundingRateResp.class, false);
    }

    public  GetIndexPriceResp getIndexPrice(GetIndexPriceReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/index-price", req, GetIndexPriceResp.class, false);
    }

    public  GetKlinesResp getKlines(GetKlinesReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/kline", req, GetKlinesResp.class, false);
    }

    public  GetOpenInterestResp getOpenInterest(GetOpenInterestReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/open-interest", req, GetOpenInterestResp.class, false);
    }

    public  GetOrderBookResp getOrderBook(GetOrderBookReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/orderbook", req, GetOrderBookResp.class, false);
    }

    public  GetPositionTiersResp getPositionTiers(GetPositionTiersReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/position-tiers", req, GetPositionTiersResp.class, false);
    }

    public  GetTickerResp getTicker(GetTickerReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/ticker", req, GetTickerResp.class, false);
    }

    public  GetTradeResp getTrade(GetTradeReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/trade", req, GetTradeResp.class, false);
    }

    public  GetOEScurrencyResp getOEScurrency(GetOEScurrencyReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/oes/currency", req, GetOEScurrencyResp.class, false);
    }

    public  GetServiceStatusResp getServiceStatus(GetServiceStatusReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/server/status", req, GetServiceStatusResp.class, false);
    }

    public  GetKYCRegionsResp getKYCRegions(){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/user/kyc-region", null, GetKYCRegionsResp.class, false);
    }

    public  GetClientIPAddressResp getClientIPAddress(){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/user/my-ip", null, GetClientIPAddressResp.class, false);
    }

    public  GetCallAuctionInfoResp getCallAuctionInfo(GetCallAuctionInfoReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/call-auction-info", req, GetCallAuctionInfoResp.class, false);
    }

    public  GetCurrenciesResp getCurrencies(GetCurrenciesReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/asset/currencies", req, GetCurrenciesResp.class, false);
    }

    public  GetCurrencyResp getCurrency(GetCurrencyReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/currency", req, GetCurrencyResp.class, false);
    }

    public  GetMaxOrderQuantityResp getMaxOrderQuantity(GetMaxOrderQuantityReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/order/max-order-quantity", req, GetMaxOrderQuantityResp.class, false);
    }

    public  GetFiatPriceResp getFiatPrice(GetFiatPriceReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/fiat-price", req, GetFiatPriceResp.class, false);
    }

    public  GetSymbolResp getSymbol(GetSymbolReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/instrument", req, GetSymbolResp.class, false);
    }

    public  GetTradeStatisticsResp getTradeStatistics(){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/trade-statistics", null, GetTradeStatisticsResp.class, false);
    }

    public  GetCurrentFundingRatesResp getCurrentFundingRates(GetCurrentFundingRatesReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/funding-rate", req, GetCurrentFundingRatesResp.class, false);
    }

    public  GetInterestRateIndexResp getInterestRateIndex(GetInterestRateIndexReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/market/interest-rate-index", req, GetInterestRateIndexResp.class, false);
    }

}