// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.market;

public interface MarketApi {
    /**
    * Get Announcements
    *
    * <p>:::info[Description] This interface can obtain the latest news announcements, and the default page search is for announcements within a month. ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    */

    GetAnnouncementsResp getAnnouncements(GetAnnouncementsReq req);

    /**
    * Get Borrowable Currencies
    *
    * <p>:::info[Description] Retrieve the list of borrowable currencies, only supported in UTA mode. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 15
    * </ul>
    *
    */

    GetBorrowableCurrenciesResp getBorrowableCurrencies();

    /**
    * Get Collateral Ratio
    *
    * <p>:::info[Description] Get Collateral Ratio for UTA. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 10
    * </ul>
    *
    */

    GetCollateralRatioResp getCollateralRatio();

    /**
    * Get History Funding Rate
    *
    * <p>:::info[Description] Query the Futures funding rate at each settlement time point within a certain time range of the corresponding contract.  :::  
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    GetHistoryFundingRateResp getHistoryFundingRate(GetHistoryFundingRateReq req);

    /**
    * Get Index Price
    *
    * <p>:::info[Description] Request Index Price (Update snapshots once per second) :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 2
    * </ul>
    *
    */

    GetIndexPriceResp getIndexPrice(GetIndexPriceReq req);

    /**
    * Get Klines
    *
    * <p>:::info[Description] Get Symbol Klines  1. Total historical time range - Spot: no limit on historical range - Futures: for intervals shorter than 8 hours, only data after 2025-01-01 is available; for other intervals, there is no limit 2. Maximum query range per request Data is returned in grouped time buckets based on the requested interval. To retrieve more data, please paginate by time.  - Spot: up to 1,500 records per request - Futures: up to 200 records per request :::  :::tip[Tips] Klines data may be incomplete. No data is published for intervals where there are no ticks. ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetKlinesResp getKlines(GetKlinesReq req);

    /**
    * Get Futures Open Interest
    *
    * <p>:::info[Description]  **Historical OI (By Interval)**  1. &#x60;interval&#x60; is required. - Historical data is available starting from Dec 29, 2025.  | Interval | Max Retention | | --- | --- | | 5min, 15min, 30min, 1hour, 4hour | 7 days | | 1day | 70 days |  2. &#x60;symbol&#x60; is required and must be a single symbol (multiple symbols are not supported). 3. Pagination is supported. - You can query within a time range using &#x60;pageSize&#x60;, &#x60;startAt&#x60;, &#x60;endAt&#x60;. - &#x60;endAt&#x60; can be treated as the lastId.  **Real-time OI**  1. &#x60;symbol&#x60; supports up to 10 unique symbols. If &#x60;symbol&#x60; is not specified, all symbols are returned. 3. The following filters are not effective for real-time queries: &#x60;startAt&#x60;, &#x60;endAt&#x60;, &#x60;pageSize&#x60;. :::   
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 10
    * </ul>
    *
    */

    GetOpenInterestResp getOpenInterest(GetOpenInterestReq req);

    /**
    * Get OrderBook
    *
    * <p>:::info[Description] Query order book depth information (aggregated by price).  Full depth is typically used by professional traders, as it consumes more server resources and bandwidth, and we have strict access rate limits. Support deep queries for call auctions, and the serial numbers of call auctions and continuous trading periods are not synchronized.  To maintain the latest order book information, we recommend using WebSocket incremental push to retrieve depth information. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetOrderBookResp getOrderBook(GetOrderBookReq req);

    /**
    * Get Position Tiers
    *
    * <p>:::info[Description]  ### Risk Limit Overview  | # | Account Type | Margin Mode | Risk Limit | Reference | | ---: | --- | --- | --- | --- | | 1 | Classic Account | Futures Isolated | User must set Risk Limit. | [Get Isolated Margin Risk Limit](apidog://link/endpoint/3470263)&lt;br&gt;[Modify Isolated Margin Risk Limit](apidog://link/endpoint/3470264) | | 2 | Classic Account | Futures Cross | Risk Limit is a continuous value. Query via API. | [Get Cross Margin Risk Limit](apidog://link/endpoint/3472655) | | 3 | Unified Trading Account | Futures | Risk Limit is tiered. No manual setting. System applies the minimum tier based on the current tier. Leverage determines the maximum position size that can be opened. The current position size + the total notional value of open orders determines the maintenance margin ratio. | [References](https://www.kucoin.com/futures/contract/risk-limit/XBTUSDTM) |  :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 15
    * </ul>
    *
    */

    GetPositionTiersResp getPositionTiers(GetPositionTiersReq req);

    /**
    * Get Ticker
    *
    * <p>:::info[Description] Request market tickers for the trading pairs in the market (including 24h volume);   takes a snapshot every 2 seconds.  In rare cases, we may change the currency name. If you still need the changed symbol name, you can use the “name“ instead of the ”symbol“ (but still need to use the symbol for normal transactions). :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 15
    * </ul>
    *
    */

    GetTickerResp getTicker(GetTickerReq req);

    /**
    * Get Trades
    *
    * <p>:::info[Description] Request via this endpoint to get the latest 100 public trades of the specified symbol :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetTradeResp getTrade(GetTradeReq req);

    /**
    * Get Third-Party Custody Currencies
    *
    * <p>:::info[Description] Support querying the settlement currency supported by the specified custodian institution. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 15
    * </ul>
    *
    */

    GetOEScurrencyResp getOEScurrency(GetOEScurrencyReq req);

    /**
    * Get Service Status
    *
    * <p>:::info[Description] Get the service status. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetServiceStatusResp getServiceStatus(GetServiceStatusReq req);

    /**
    * Get KYC Regions
    *
    * <p>:::info[Description] This endpoint can be used to obtain this users kyc regions. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 20
    * </ul>
    *
    */

    GetKYCRegionsResp getKYCRegions();

    /**
    * Get Client IP Address
    *
    * <p>:::info[Description] Get the client side IP address. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 10
    * </ul>
    *
    */

    GetClientIPAddressResp getClientIPAddress();

    /**
    * Get Call Auction Info
    *
    * <p>Get [call auction](https://www.kucoin.com/support/40999744334105) data,. This interface will return the following information for the specified symbol during the call auction phase: estimated transaction price, estimated transaction quantity, bid price range, and ask price range.
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 2
    * </ul>
    *
    */

    GetCallAuctionInfoResp getCallAuctionInfo(GetCallAuctionInfoReq req);

    /**
    * Get Currencies
    *
    * <p>:::info[Description] Get currency and chain-level configuration, including deposit/withdrawal availability, precision, fees, limits, and memo/tag requirements. :::  :::tip[Usage] Use &#x60;currencyList&#x60; to filter currencies and &#x60;chain&#x60; to filter a blockchain network. Currency values use uppercase codes, while chain values use lowercase identifiers. When a currency supports multiple chains, use the returned &#x60;list[].chain&#x60; value in related V2 asset APIs such as deposit address, withdrawal quotas, and withdrawal requests. :::  :::info[Field relationship] &#x60;chain&#x60; is the API request value, for example &#x60;trx&#x60;. &#x60;chainName&#x60; is the display name, for example &#x60;TRC20&#x60;. Use &#x60;chain&#x60; when passing the selected network to other V2 asset APIs. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetCurrenciesResp getCurrencies(GetCurrenciesReq req);

    /**
    * Get Currency
    *
    * <p>:::info[Description] Get currency configuration for a specified currency and optional chain, including deposit/withdrawal availability, confirmation counts, memo/tag requirements, and contract information. :::  :::tip[Usage] Use this endpoint to look up the available &#x60;chain&#x60; values for a currency before calling related V2 asset APIs such as deposit address, withdrawal quotas, or withdrawal requests. :::  :::info[Field relationship] &#x60;chain&#x60; is the API request value, for example &#x60;trx&#x60;. &#x60;chainName&#x60; is the display name, for example &#x60;TRC20&#x60;. Confirmation counts and contract addresses are returned at chain level under &#x60;list[]&#x60;. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetCurrencyResp getCurrency(GetCurrencyReq req);

    /**
    * Get Max Order Quantity
    *
    * <p>Get the maximum buy and sell quantity available for a symbol in the unified account. If price is not provided, the request reuses the existing max-available pricing logic.
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 10
    * </ul>
    *
    */

    GetMaxOrderQuantityResp getMaxOrderQuantity(GetMaxOrderQuantityReq req);

    /**
    * Get Fiat Price
    *
    * <p>:::info[Description] Retrieve fiat conversion prices for specified currencies. The &#x60;base&#x60; parameter is the fiat currency used for pricing, and &#x60;currencies&#x60; contains uppercase crypto currency codes such as &#x60;BTC&#x60;, &#x60;ETH&#x60;, or &#x60;USDT&#x60;. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetFiatPriceResp getFiatPrice(GetFiatPriceReq req);

    /**
    * Get Symbol
    *
    * <p>:::info[Description] Get symbol information for a specified product type. This endpoint supports &#x60;SPOT&#x60; and &#x60;FUTURES&#x60;. :::  :::tip[Order rules] Use the size, funds, and price increment fields returned for the selected &#x60;tradeType&#x60; to validate order input before placing orders. The order price must follow the &#x60;tickSize&#x60; increment, and order size or funds must satisfy the corresponding minimum and maximum limits. :::  :::info[Product-specific fields] Some response fields are product-specific. Spot-only fields are marked with &#x60;(Only applicable to spot)&#x60;, and futures-only fields are marked with &#x60;(Only applicable to futures)&#x60;. Always read the example for the requested &#x60;tradeType&#x60; before mapping response fields. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 4
    * </ul>
    *
    */

    GetSymbolResp getSymbol(GetSymbolReq req);

    /**
    * Platform 24h Market Statistics
    *
    * <p>Get the platform&#39;s 24h market statistics, including spot and futures.
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetTradeStatisticsResp getTradeStatistics();

    /**
    * Get Current Funding Rate
    *
    * <p>Get current Futures funding fee rates by contract symbol or product type.
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    */

    GetCurrentFundingRatesResp getCurrentFundingRates(GetCurrentFundingRatesReq req);

    /**
    * Get Interest Rate Index
    *
    * <p>Get futures interest rate records by symbol with optional time range and pagination cursor.
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PUBLIC
    * <li>API-PERMISSION         : NULL
    * <li>API-RATE-LIMIT-POOL    : PUBLIC
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    */

    GetInterestRateIndexResp getInterestRateIndex(GetInterestRateIndexReq req);

}