// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ApiChangeMarginModeResponse {
    /**
    * 
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * 
    */
    @JsonProperty("items")
    private List<ApiChangeMarginModeVo> items = new ArrayList<>();



}
