// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GenericResultApiChangeMarginModeResponse {
    /**
    * 
    */
    @JsonProperty("msg")
    private String msg;

    /**
    * 
    */
    @JsonProperty("code")
    private String code;

    /**
    * 
    */
    @JsonProperty("data")
    private ApiChangeMarginModeResponse data;



}
