// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetPositionsHistoryReq implements Request {
    /**
    * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](apidog://link/endpoint/3470220) 
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Start time (Unix timestamp in milliseconds)
    */
    @JsonProperty("startAt")
    private Long startAt;

    /**
    * End time (Unix timestamp in milliseconds)
    */
    @JsonProperty("endAt")
    private Long endAt;

    /**
    * ID of the last record from the previous query (used for cursor-based pagination)
    */
    @JsonProperty("lastId")
    @Builder.Default
    private Long lastId = 10l;

    /**
    * Number of records per page
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 1L;



}
