// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetPositionListReq implements Request {
    /**
    * Symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Page Number
    */
    @JsonProperty("pageNumber")
    @Builder.Default
    private String pageNumber = "1";

    /**
    * Page Size
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private String pageSize = "50";



}
