// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetPrivateFundingFeeHistoryReq implements Request {
    /**
    * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](apidog://link/endpoint/3470220) 
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Start time, in milliseconds.
    */
    @JsonProperty("startAt")
    private Long startAt;

    /**
    * End time, in milliseconds. The time range between startAt and endAt cannot exceed 90 days.
    */
    @JsonProperty("endAt")
    private Long endAt;

    /**
    * The ID of the last set of data from the previous data batch. By default, the latest information is given.
    */
    @JsonProperty("lastId")
    private Long lastId;

    /**
    * Specifies the number of records to return per page.
    */
    @JsonProperty("pageSize")
    @Builder.Default
    private Long pageSize = 50L;



}
