// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetPositionListData {
    /**
    * Contract symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Unique position identifier
    */
    @JsonProperty("id")
    private String id;

    /**
    * Margin mode
    */
    @JsonProperty("marginMode")
    private MarginModeEnum marginMode;

    /**
    * Position size in contracts (positive = long, negative = short)
    */
    @JsonProperty("size")
    private String size;

    /**
    * Average entry price of the position
    */
    @JsonProperty("entryPrice")
    private String entryPrice;

    /**
    * Current position value in settlement currency
    */
    @JsonProperty("positionValue")
    private String positionValue;

    /**
    * Position margin. For Cross Margin mode, it is calculated as position value based on mark price divided by leverage. For Isolated Margin mode, it is the margin allocated to the position and can be manually adjusted.
    */
    @JsonProperty("positionMargin")
    private String positionMargin;

    /**
    * Current mark price used for unrealized PnL and liquidation calculations
    */
    @JsonProperty("markPrice")
    private String markPrice;

    /**
    * Position leverage
    */
    @JsonProperty("leverage")
    private String leverage;

    /**
    * Current unrealized profit and loss
    */
    @JsonProperty("unrealizedPnL")
    private String unrealizedPnL;

    /**
    * Accumulated realized profit and loss (from partial closes, funding, fees, etc.)
    */
    @JsonProperty("realizedPnL")
    private String realizedPnL;

    /**
    * Initial margin required for the position
    */
    @JsonProperty("initialMargin")
    private String initialMargin;

    /**
    * Maintenance Margin Rate (MMR)
    */
    @JsonProperty("mmr")
    private String mmr;

    /**
    * Current maintenance margin amount
    */
    @JsonProperty("maintenanceMargin")
    private String maintenanceMargin;

    /**
    * Timestamp when the position was first opened (nanoseconds)
    */
    @JsonProperty("creationTime")
    private Long creationTime;

    /**
    * Estimated liquidation price
    */
    @JsonProperty("liquidationPrice")
    private String liquidationPrice;

    /**
    * Risk ratio of an **isolated futures** position. For example, 0.65 represents 65%. When the risk ratio is greater than or equal to 1 (100%), liquidation will be triggered. For the cross margin risk ratio, please refer to `riskRatio` in the \"Get Account Overview (UTA)\" endpoint.
    */
    @JsonProperty("riskRatio")
    private String riskRatio;

    /**
    * ADL ranking percentile of the futures position. The higher the value, the more likely it is to be triggered for ADL. For example, 0.12 indicates a ranking position at 12%.
    */
    @JsonProperty("adlPercentage")
    private String adlPercentage;

    /**
    * The latest time when the position is updated (including the  leverage change and the size change for position
    */
    @JsonProperty("updateTime")
    private Long updateTime;



    public enum MarginModeEnum {
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        ISOLATED("ISOLATED");

        private final String value;

        MarginModeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static MarginModeEnum fromValue(String value) {
          for (MarginModeEnum b :  MarginModeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
