// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetPositionsHistoryResp implements Response<GetPositionsHistoryResp, RestResponse<GetPositionsHistoryResp>> {
    /**
    * 
    */
    @JsonProperty("items")
    private List<GetPositionsHistoryItems> items = new ArrayList<>();

    /**
    * The closeId of the last item in the current page (for pagination cursor)
    */
    @JsonProperty("lastId")
    private Long lastId;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<GetPositionsHistoryResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<GetPositionsHistoryResp> response) {
        this.commonResponse = response;
    }



}
