// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetPositionsHistoryItems {
    /**
    * Unique ID of the closed position
    */
    @JsonProperty("closeId")
    private String closeId;

    /**
    * Contract symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Margin mode
    */
    @JsonProperty("marginMode")
    private MarginModeEnum marginMode;

    /**
    * Position side
    */
    @JsonProperty("side")
    private SideEnum side;

    /**
    * Average entry price of the position
    */
    @JsonProperty("entryPrice")
    private String entryPrice;

    /**
    * Final closing price
    */
    @JsonProperty("closePrice")
    private String closePrice;

    /**
    * Average closing price
    */
    @JsonProperty("avgClosePrice")
    private String avgClosePrice;

    /**
    * Maximum position size
    */
    @JsonProperty("maxSize")
    private String maxSize;

    /**
    * Leverage used
    */
    @JsonProperty("leverage")
    private String leverage;

    /**
    * Realized profit and loss (after fees and funding)
    */
    @JsonProperty("realizedPnL")
    private String realizedPnL;

    /**
    * Total trading fee for this position
    */
    @JsonProperty("fee")
    private String fee;

    /**
    * Tax amount
    */
    @JsonProperty("tax")
    private String tax;

    /**
    * Accumulated funding fee for this position
    */
    @JsonProperty("fundingFee")
    private String fundingFee;

    /**
    * Position opening timestamp (nanoseconds)
    */
    @JsonProperty("creationTime")
    private Long creationTime;

    /**
    * Position closing timestamp (nanoseconds)
    */
    @JsonProperty("closingTime")
    private Long closingTime;



    public enum MarginModeEnum {
        /**
        * 
        */
        CROSS("CROSS"),
        /**
        * 
        */
        ISOLATED("ISOLATED");

        private final String value;

        MarginModeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static MarginModeEnum fromValue(String value) {
          for (MarginModeEnum b :  MarginModeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum SideEnum {
        /**
        * 
        */
        LONG("LONG"),
        /**
        * 
        */
        SHORT("SHORT");

        private final String value;

        SideEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static SideEnum fromValue(String value) {
          for (SideEnum b :  SideEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
