// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ModifyIsolatedFuturesMarginReq implements Request {
    /**
    * 
    */
    @JsonProperty("type")
    private TypeEnum type;

    /**
    * Absolute value of margin to add/reduce, positive integer
    */
    @JsonProperty("amount")
    private Double amount;

    /**
    * Trading pair symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Only FUTURES applicable
    */
    @JsonProperty("tradeType")
    private TradeTypeEnum tradeType;



    public enum TypeEnum {
        /**
        * 
        */
        DEPOSIT("DEPOSIT"),
        /**
        * 
        */
        WITHDRAW("WITHDRAW");

        private final String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
          for (TypeEnum b :  TypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public enum TradeTypeEnum {
        /**
        * 
        */
        FUTURES("FUTURES");

        private final String value;

        TradeTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
          return value;
        }

        @Override
        public String toString() {
          return String.valueOf(value);
        }

        @JsonCreator
        public static TradeTypeEnum fromValue(String value) {
          for (TradeTypeEnum b :  TradeTypeEnum.values()) {
            if (b.value.equals(value)) {
              return b;
            }
          }
          throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
}
