// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ModifyIsolatedFuturesMarginResp implements Response<ModifyIsolatedFuturesMarginResp, RestResponse<ModifyIsolatedFuturesMarginResp>> {
    /**
    * 
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<ModifyIsolatedFuturesMarginResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<ModifyIsolatedFuturesMarginResp> response) {
        this.commonResponse = response;
    }



}
