// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ModifyMarginModeItems {
    /**
    * Modification result for this trading pair
    */
    @JsonProperty("msg")
    private String msg;

    /**
    * Response code
    */
    @JsonProperty("code")
    private String code;

    /**
    * Trading pair symbol
    */
    @JsonProperty("symbol")
    private String symbol;

    /**
    * Margin mode updated for this pair
    */
    @JsonProperty("marginMode")
    private String marginMode;



}
