// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ModifyMarginModeResp implements Response<ModifyMarginModeResp, RestResponse<ModifyMarginModeResp>> {
    /**
    * Timestamp
    */
    @JsonProperty("ts")
    private Long ts;

    /**
    * 
    */
    @JsonProperty("items")
    private List<ModifyMarginModeItems> items = new ArrayList<>();

    /**
    * common response
    */
    @JsonIgnore
    private RestResponse<ModifyMarginModeResp> commonResponse;

    @Override
    public void setCommonResponse(RestResponse<ModifyMarginModeResp> response) {
        this.commonResponse = response;
    }



}
