// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;
import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class PositionsApiImpl implements PositionsApi {
    private final Transport transport;

    public PositionsApiImpl(Transport transport)
    {
        this.transport = transport;
    }

    public  GetPrivateFundingFeeHistoryResp getPrivateFundingFeeHistory(GetPrivateFundingFeeHistoryReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/position/funding-history", req, GetPrivateFundingFeeHistoryResp.class, false);
    }

    public  GetPositionsHistoryResp getPositionsHistory(GetPositionsHistoryReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/position/history", req, GetPositionsHistoryResp.class, false);
    }

    public  GetMarginModeResp getMarginMode(GetMarginModeReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/unified/position/margin-mode", req, GetMarginModeResp.class, false);
    }

    public  GetPositionListResp getPositionList(GetPositionListReq req){
        return this.transport.call("spot", false, "GET", "/api/ua/v2/unified/position/open-list", req, GetPositionListResp.class, false);
    }

    public  ModifyMarginModeResp modifyMarginMode(ModifyMarginModeReq req){
        return this.transport.call("spot", false, "POST", "/api/ua/v2/unified/position/margin-mode", req, ModifyMarginModeResp.class, false);
    }

    public  ModifyIsolatedFuturesMarginResp modifyIsolatedFuturesMargin(ModifyIsolatedFuturesMarginReq req){
        return this.transport.call("spot", false, "POST", "/api/ua/v2/unified/position/modify-margin", req, ModifyIsolatedFuturesMarginResp.class, false);
    }

}