// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.uta.positions;

public interface PositionsApi {
    /**
    * Get Private Funding Fee History
    *
    * <p>:::info[Description] Retrieve settled funding fee records for the current account. :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 15
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetPrivateFundingFeeHistoryResp getPrivateFundingFeeHistory(GetPrivateFundingFeeHistoryReq req);

    /**
    * Get Positions History
    *
    * <p>:::info[Description] This interface allows users to query futures position history information records. :::  :::tip[Data Time Range] The data is retained in the system for up to three months. Queries are permitted within this retention period (i.e., from the current time to three months prior). However, each individual query is limited to a time range of 7 × 24 hours (i.e., up to one week). If the specified time range exceeds this limit, the system will default to retrieving data within the maximum allowable 7 × 24-hour window. To access data spanning beyond 7 × 24 hours, multiple queries are required. ::: 
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 2
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetPositionsHistoryResp getPositionsHistory(GetPositionsHistoryReq req);

    /**
    * Get Margin Mode
    *
    * <p>This endpoint allows users to query the current margin mode of a futures symbol (Isolated or Cross).
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 10
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetMarginModeResp getMarginMode(GetMarginModeReq req);

    /**
    * Get Position List
    *
    * <p>:::info[Description] Get the position details of all **futures open positions**, Sort by Symbol ID (Internal ID sorting, not alphabetical sorting) :::
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 3
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    GetPositionListResp getPositionList(GetPositionListReq req);

    /**
    * Modify Margin Mode
    *
    * <p>Batch modify the margin mode for futures positions
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : MANAGEMENT
    * <li>API-RATE-LIMIT-WEIGHT  : 10
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    ModifyMarginModeResp modifyMarginMode(ModifyMarginModeReq req);

    /**
    * Modify Position Margin
    *
    * <p>Extract or add margin for an isolated futures position.
    *
    * <p>Extra API Info:
    *
    * <ul>
    * <li>API-DOMAIN             : SPOT
    * <li>API-CHANNEL            : PRIVATE
    * <li>API-PERMISSION         : GENERAL
    * <li>API-RATE-LIMIT-POOL    : UNIFIED ACCOUNT
    * <li>API-RATE-LIMIT-WEIGHT  : 5
    * </ul>
    *
    * @see <a href="">docs</a>
    */

    ModifyIsolatedFuturesMarginResp modifyIsolatedFuturesMargin(ModifyIsolatedFuturesMarginReq req);

}